import logging
import math
from functools import lru_cache
from pathlib import Path
from typing import Optional

import nibabel as nib
import numpy as np
from ndx_anatomical_localization import AnatomicalCoordinatesTable, Localization, Space
from pydantic import FilePath
from pynwb import NWBFile

from neuroconv.basedatainterface import BaseDataInterface

logger = logging.getLogger(__name__)

_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent.parent

# D99 atlas data directory (relative to project root).
# Required files (download from https://afni.nimh.nih.gov/pub/dist/atlases/macaque/d99/D99_v2.0_dist.tgz):
#   - D99_atlas_v2.0.nii.gz  (813K, parcellation volume)
#   - D99_v2.0_labels_semicolon.txt  (20K, label names)
# Extract to: <project_root>/data/d99_atlas/D99_v2.0_dist/
_D99_ATLAS_DIR = _PROJECT_ROOT / "data" / "d99_atlas" / "D99_v2.0_dist"

# RheMAP warp file for D99 -> NMT v2.0-sym coordinate conversion.
# Download from https://zenodo.org/records/4748589 (warps_final_NMTv2.0-sym.zip).
# For point transforms, the warp direction is REVERSED: use the NMTv2.0-sym_to_D99 warp
# to move a point FROM D99 TO NMT v2.0-sym (ANTs convention).
_RHEMAP_WARP_PATH = _PROJECT_ROOT / "data" / "rhemap_warps" / "NMTv2.0-sym_to_D99_CompositeWarp.nii.gz"

# RheMAP warp file for D99 -> MEBRAINS coordinate conversion.
# Download from https://gin.g-node.org/ChrisKlink/RheMAP (warps/final/).
# Same reversed-direction ANTs convention as the NMT warp above.
_MEBRAINS_WARP_PATH = _PROJECT_ROOT / "data" / "rhemap_warps" / "MEBRAINS_to_D99_CompositeWarp.nii.gz"

# Precomputed warp results (CSV). Generated by scripts/precompute_warped_coordinates.py.
# Contains D99 -> NMT and D99 -> MEBRAINS coordinates for all unique electrode positions.
# This avoids calling ANTs at conversion time (~3s per warp, ~30 min for 358 sessions).
_WARPED_COORDS_PATH = (
    _PROJECT_ROOT / "src" / "turner_lab_to_nwb" / "asap_m1_mptp"
    / "assets" / "metadata_table" / "warped_coordinates.csv"
)


@lru_cache(maxsize=1)
def _load_d99_atlas() -> tuple[np.ndarray, np.ndarray, dict]:
    """Load D99 atlas data (cached across sessions).

    Returns
    -------
    atlas_data : np.ndarray
        3D array of label IDs
    inv_affine : np.ndarray
        Inverse affine matrix (world RAS mm -> voxel indices)
    labels : dict
        Mapping from label_id to {"abbreviation": str, "full_name": str}
    """
    atlas_path = _D99_ATLAS_DIR / "D99_atlas_v2.0.nii.gz"
    labels_path = _D99_ATLAS_DIR / "D99_v2.0_labels_semicolon.txt"

    atlas = nib.load(str(atlas_path))
    atlas_data = np.asarray(atlas.dataobj)
    inv_affine = np.linalg.inv(atlas.affine)

    # Parse label file: id;abbreviation;full_name[;category;subcategory]
    labels = {}
    with open(labels_path) as f:
        for line in f:
            parts = line.strip().split(";")
            if len(parts) >= 3:
                label_id = int(parts[0])
                abbreviation = parts[1].strip()
                full_name = parts[2].strip().strip('"')
                labels[label_id] = {"abbreviation": abbreviation, "full_name": full_name}

    return atlas_data, inv_affine, labels


@lru_cache(maxsize=1)
def _load_warped_coordinates():
    """Load precomputed warped coordinates CSV (cached across sessions).

    Returns a dict mapping (d99_r, d99_a, d99_s) rounded keys to
    (nmt_r, nmt_a, nmt_s, mebrains_r, mebrains_a, mebrains_s) tuples.
    """
    import pandas as pd

    if not _WARPED_COORDS_PATH.exists():
        raise FileNotFoundError(
            f"Precomputed warp file not found at {_WARPED_COORDS_PATH}. "
            "Run: uv run python src/turner_lab_to_nwb/asap_m1_mptp/scripts/precompute_warped_coordinates.py"
        )

    df = pd.read_csv(_WARPED_COORDS_PATH)
    lookup = {}
    for _, row in df.iterrows():
        key = (round(row["d99_r"], 6), round(row["d99_a"], 6), round(row["d99_s"], 6))
        lookup[key] = (
            row["nmt_r"], row["nmt_a"], row["nmt_s"],
            row["mebrains_r"], row["mebrains_a"], row["mebrains_s"],
        )
    return lookup


def lookup_warped_coordinates(
    d99_r: float, d99_a: float, d99_s: float
) -> tuple[float, float, float, float, float, float]:
    """Look up precomputed NMT and MEBRAINS coordinates for a D99 RAS position.

    Parameters
    ----------
    d99_r, d99_a, d99_s : float
        D99 RAS coordinates (mm)

    Returns
    -------
    tuple of (nmt_r, nmt_a, nmt_s, mebrains_r, mebrains_a, mebrains_s)

    Raises
    ------
    KeyError
        If the coordinate is not in the precomputed table. Regenerate with:
        uv run python src/turner_lab_to_nwb/asap_m1_mptp/scripts/precompute_warped_coordinates.py
    """
    lookup = _load_warped_coordinates()
    key = (round(d99_r, 6), round(d99_a, 6), round(d99_s, 6))
    if key not in lookup:
        raise KeyError(
            f"D99 coordinate ({d99_r}, {d99_a}, {d99_s}) not found in precomputed warp table. "
            "Regenerate with: uv run python src/turner_lab_to_nwb/asap_m1_mptp/scripts/precompute_warped_coordinates.py"
        )
    return lookup[key]


def lookup_d99_region(ap_acx: float, ml_acx: float, depth_acx: float) -> tuple[str, str]:
    """Look up the D99 atlas region for a given ACx coordinate.

    Parameters
    ----------
    ap_acx : float
        Anterior-posterior coordinate (+anterior, mm)
    ml_acx : float
        Medial-lateral coordinate (+lateral left, mm)
    depth_acx : float
        Depth coordinate (+superior/dorsal, mm)

    Returns
    -------
    full_name : str
        Full region name from D99 labels
    abbreviation : str
        Region abbreviation from D99 labels
    """
    atlas_data, inv_affine, labels = _load_d99_atlas()

    # Convert ACx to D99 RAS world coordinates (AC is at origin 0,0,0)
    r = -ml_acx  # left hemisphere = negative R
    a = ap_acx
    s = depth_acx

    world_coord = np.array([r, a, s])
    voxel = nib.affines.apply_affine(inv_affine, world_coord)
    voxel_idx = tuple(np.round(voxel).astype(int))

    # Check bounds
    if all(0 <= voxel_idx[i] < atlas_data.shape[i] for i in range(3)):
        label_id = int(atlas_data[voxel_idx])
        if label_id > 0 and label_id in labels:
            return labels[label_id]["full_name"], labels[label_id]["abbreviation"]

    return "outside atlas", "outside"


def convert_d99_to_nmt(r_d99: float, a_d99: float, s_d99: float) -> tuple[float, float, float]:
    """Convert a D99 RAS coordinate (mm) to NMT v2.0-sym RAS (mm) using a RheMAP warp.

    Uses the pre-computed nonlinear warp from RheMAP (Sirmpilatze & Klink, 2020).
    ANTs operates in LPS+ internally, so RAS coordinates are converted to LPS before
    applying the warp and converted back afterward. For point transforms, the warp
    direction is reversed: the NMTv2.0-sym_to_D99 warp moves points FROM D99 TO NMT.

    Parameters
    ----------
    r_d99 : float
        Right coordinate in D99 RAS (mm)
    a_d99 : float
        Anterior coordinate in D99 RAS (mm)
    s_d99 : float
        Superior coordinate in D99 RAS (mm)

    Returns
    -------
    tuple of (r_nmt, a_nmt, s_nmt) in NMT v2.0-sym RAS (mm).

    Raises
    ------
    FileNotFoundError
        If the RheMAP warp file is not found.
    """
    if not _RHEMAP_WARP_PATH.exists():
        raise FileNotFoundError(
            f"RheMAP warp file not found at {_RHEMAP_WARP_PATH}. "
            "Download warps_final_NMTv2.0-sym.zip from https://zenodo.org/records/4748589 "
            "and extract NMTv2.0-sym_to_D99_CompositeWarp.nii.gz to data/rhemap_warps/"
        )

    import ants
    import pandas as pd

    # RAS to LPS (negate R and A)
    l_d99 = -r_d99
    p_d99 = -a_d99
    s_lps = s_d99

    points = pd.DataFrame({"x": [l_d99], "y": [p_d99], "z": [s_lps]})

    transformed = ants.apply_transforms_to_points(
        dim=3,
        points=points,
        transformlist=[str(_RHEMAP_WARP_PATH)],
    )

    # LPS back to RAS (negate L and P)
    r_nmt = -transformed["x"].values[0]
    a_nmt = -transformed["y"].values[0]
    s_nmt = transformed["z"].values[0]

    return (float(r_nmt), float(a_nmt), float(s_nmt))


def batch_convert_d99_to_nmt(
    r_d99: np.ndarray, a_d99: np.ndarray, s_d99: np.ndarray
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Convert multiple D99 RAS coordinates to NMT v2.0-sym RAS in a single warp call.

    Same as convert_d99_to_nmt but processes all coordinates at once, which is
    much faster (~3s total vs ~3s per coordinate) since the warp field is loaded once.

    Parameters
    ----------
    r_d99, a_d99, s_d99 : np.ndarray
        Arrays of D99 RAS coordinates (mm)

    Returns
    -------
    tuple of (r_nmt, a_nmt, s_nmt) arrays in NMT v2.0-sym RAS (mm).

    Raises
    ------
    FileNotFoundError
        If the RheMAP warp file is not found.
    """
    if not _RHEMAP_WARP_PATH.exists():
        raise FileNotFoundError(
            f"RheMAP warp file not found at {_RHEMAP_WARP_PATH}. "
            "Download warps_final_NMTv2.0-sym.zip from https://zenodo.org/records/4748589 "
            "and extract NMTv2.0-sym_to_D99_CompositeWarp.nii.gz to data/rhemap_warps/"
        )

    import ants
    import pandas as pd

    points = pd.DataFrame({"x": -np.asarray(r_d99), "y": -np.asarray(a_d99), "z": np.asarray(s_d99)})
    transformed = ants.apply_transforms_to_points(dim=3, points=points, transformlist=[str(_RHEMAP_WARP_PATH)])
    return (-transformed["x"].values, -transformed["y"].values, transformed["z"].values)


def convert_d99_to_mebrains(r_d99: float, a_d99: float, s_d99: float) -> tuple[float, float, float]:
    """Convert a D99 RAS coordinate (mm) to MEBRAINS RAS (mm) using a RheMAP warp.

    Uses the pre-computed nonlinear warp from RheMAP (G-NODE repository).
    Same RAS/LPS and reversed-direction conventions as convert_d99_to_nmt.

    Parameters
    ----------
    r_d99 : float
        Right coordinate in D99 RAS (mm)
    a_d99 : float
        Anterior coordinate in D99 RAS (mm)
    s_d99 : float
        Superior coordinate in D99 RAS (mm)

    Returns
    -------
    tuple of (r, a, s) in MEBRAINS RAS (mm).

    Raises
    ------
    FileNotFoundError
        If the RheMAP warp file is not found.
    """
    if not _MEBRAINS_WARP_PATH.exists():
        raise FileNotFoundError(
            f"RheMAP warp file not found at {_MEBRAINS_WARP_PATH}. "
            "Download from https://gin.g-node.org/ChrisKlink/RheMAP (warps/final/) "
            "and place MEBRAINS_to_D99_CompositeWarp.nii.gz in data/rhemap_warps/"
        )

    import ants
    import pandas as pd

    # RAS to LPS (negate R and A)
    points = pd.DataFrame({"x": [-r_d99], "y": [-a_d99], "z": [s_d99]})

    transformed = ants.apply_transforms_to_points(
        dim=3,
        points=points,
        transformlist=[str(_MEBRAINS_WARP_PATH)],
    )

    # LPS back to RAS (negate L and P)
    r_mebrains = -transformed["x"].values[0]
    a_mebrains = -transformed["y"].values[0]
    s_mebrains = transformed["z"].values[0]

    return (float(r_mebrains), float(a_mebrains), float(s_mebrains))


def batch_convert_d99_to_mebrains(
    r_d99: np.ndarray, a_d99: np.ndarray, s_d99: np.ndarray
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Convert multiple D99 RAS coordinates to MEBRAINS RAS in a single warp call.

    Same as convert_d99_to_mebrains but processes all coordinates at once.

    Parameters
    ----------
    r_d99, a_d99, s_d99 : np.ndarray
        Arrays of D99 RAS coordinates (mm)

    Returns
    -------
    tuple of (r, a, s) arrays in MEBRAINS RAS (mm).

    Raises
    ------
    FileNotFoundError
        If the RheMAP warp file is not found.
    """
    if not _MEBRAINS_WARP_PATH.exists():
        raise FileNotFoundError(
            f"RheMAP warp file not found at {_MEBRAINS_WARP_PATH}. "
            "Download from https://gin.g-node.org/ChrisKlink/RheMAP (warps/final/) "
            "and place MEBRAINS_to_D99_CompositeWarp.nii.gz in data/rhemap_warps/"
        )

    import ants
    import pandas as pd

    points = pd.DataFrame({"x": -np.asarray(r_d99), "y": -np.asarray(a_d99), "z": np.asarray(s_d99)})
    transformed = ants.apply_transforms_to_points(dim=3, points=points, transformlist=[str(_MEBRAINS_WARP_PATH)])
    return (-transformed["x"].values, -transformed["y"].values, transformed["z"].values)


class M1MPTPElectrodesInterface(BaseDataInterface):
    """Data interface for Turner Lab M1 MPTP electrode setup (recording and stimulation electrodes)."""

    keywords = ("electrodes", "recording electrodes", "stimulation electrodes", "antidromic identification")
    associated_suffixes = (".mat",)
    info = "Interface for Turner Lab M1 MPTP electrode configuration including recording and stimulation electrodes"

    def __init__(
        self,
        file_path: FilePath,
        session_metadata: dict,
        verbose: bool = False,
    ):
        """
        Initialize the M1MPTPElectrodesInterface.

        Parameters
        ----------
        file_path : FilePath
            Path to the first Turner Lab .mat file (used for session metadata extraction)
        session_metadata : dict
            Metadata for all units in this session (each unit contains session-level info)
        verbose : bool, optional
            Whether to print verbose output, by default False
        """
        super().__init__(verbose=verbose)
        self.base_file_path = Path(file_path)
        self.session_metadata = session_metadata
        
        # Extract session-level info from first unit (all units have same session info)
        if self.session_metadata:
            first_unit = self.session_metadata[0]
            self.session_info = {
                "Animal": first_unit["Animal"],
                "MPTP": first_unit["MPTP"],
                "DateCollected": first_unit["DateCollected"],
                "A_P": first_unit["A_P"],
                "M_L": first_unit["M_L"],
                "Depth": first_unit["Depth"],
                "A_P_acx": first_unit.get("A_P_acx", float("nan")),
                "M_L_acx": first_unit.get("M_L_acx", float("nan")),
                "Depth_acx": first_unit.get("Depth_acx", float("nan")),
            }

    def add_to_nwbfile(self, nwbfile: NWBFile, metadata: Optional[dict] = None) -> None:
        """
        Add electrode configuration to the NWB file.

        Parameters
        ----------
        nwbfile : NWBFile
            The NWB file object to add electrode configuration to
        metadata : dict, optional
            Metadata dictionary
        """
        if metadata is None:
            metadata = self.get_metadata()

        # Create device for M1 recording electrode
        recording_device = nwbfile.create_device(
            name="DeviceMicroelectrodeRecording",
            description="Glass-coated PtIr microelectrode mounted in hydraulic microdrive (MO-95, Narishige Intl., Tokyo). "
            "Signal amplified 10^4, bandpass filtered 0.3-10kHz. Sampling: 20kHz for unit discrimination.",
        )

        # Create devices for chronically implanted stimulation electrodes
        # These are documented as devices even though they're not in the electrodes table
        # (stimulation electrode metadata is in StimulationElectrodesTable in the antidromic_identification module)
        nwbfile.create_device(
            name="DeviceMicrowirePeduncleStimulation",
            description="Custom-built PtIr microwire electrode for antidromic stimulation in cerebral peduncle. "
            "Chronically implanted for PTN identification.",
        )
        nwbfile.create_device(
            name="DeviceMicrowirePutamenStimulation1",
            description="Custom-built PtIr microwire electrode 1 of 3 for antidromic stimulation in posterolateral putamen. "
            "Chronically implanted for CSN identification.",
        )
        nwbfile.create_device(
            name="DeviceMicrowirePutamenStimulation2",
            description="Custom-built PtIr microwire electrode 2 of 3 for antidromic stimulation in posterolateral putamen. "
            "Chronically implanted for CSN identification.",
        )
        nwbfile.create_device(
            name="DeviceMicrowirePutamenStimulation3",
            description="Custom-built PtIr microwire electrode 3 of 3 for antidromic stimulation in posterolateral putamen. "
            "Chronically implanted for CSN identification.",
        )
        nwbfile.create_device(
            name="DeviceMicrowireThalamicStimulation",
            description="Custom-built PtIr microwire electrode for antidromic stimulation in VL thalamus. "
            "Chronically implanted for thalamocortical projection identification.",
        )

        # Recording electrode group for M1 chamber (left hemisphere)
        recording_electrode_group = nwbfile.create_electrode_group(
            name="ElectrodeGroupMicroelectrodeRecording",
            description="Left primary motor cortex recording within chamber-relative coordinate system. "
            "Chamber surgically positioned over left M1. Daily positions relative to chamber center. "
            "Functional verification via microstimulation (≤40μA, 10 pulses at 300Hz).",
            location="Primary motor cortex (M1), area 4, arm area",
            device=recording_device,
        )

        # Add custom columns for chamber grid coordinates and recording system metadata
        nwbfile.add_electrode_column(
            name="chamber_grid_ap_mm",
            description=(
                "Chamber grid position along the anterior-posterior axis, relative to chamber center "
                "(mm, positive = posterior). Recordings span -7 to 0 mm (all anterior to chamber center). "
                "NaN for stimulation electrodes."
            ),
        )
        nwbfile.add_electrode_column(
            name="chamber_grid_ml_mm",
            description=(
                "Chamber grid position along the medial-lateral axis, relative to chamber center "
                "(mm, positive = right). Recordings span -6 to -2 mm (all in left hemisphere). "
                "NaN for stimulation electrodes."
            ),
        )
        nwbfile.add_electrode_column(
            name="chamber_insertion_depth_mm",
            description=(
                "Electrode insertion depth from chamber reference point "
                "(mm, positive = deeper, range: 8.4-27.6mm). NaN for stimulation electrodes."
            ),
        )
        # Use D99 atlas ACx coordinates when available
        # ACx convention: A_P_acx (+anterior), M_L_acx (+lateral, left hemisphere), Depth_acx (+superior/dorsal)
        ap_acx = self.session_info["A_P_acx"]
        ml_acx = self.session_info["M_L_acx"]
        depth_acx = self.session_info["Depth_acx"]
        has_acx = not (math.isnan(ap_acx) or math.isnan(ml_acx) or math.isnan(depth_acx))

        if has_acx:
            d99_full_name, d99_abbreviation = lookup_d99_region(ap_acx, ml_acx, depth_acx)
            electrode_location = d99_full_name

            # Convert ACx convention to D99 RAS:
            # R = -M_L (left hemisphere lateral is negative R)
            # A = A_P (source A_P is +anterior, same as RAS)
            # S = Depth (both +superior/dorsal)
            d99_r = -ml_acx
            d99_a = ap_acx
            d99_s = depth_acx

            # Look up precomputed NMT and MEBRAINS coordinates (avoids calling ANTs at runtime)
            nmt_r, nmt_a, nmt_s, mebrains_r, mebrains_a, mebrains_s = lookup_warped_coordinates(d99_r, d99_a, d99_s)
        else:
            electrode_location = "Primary motor cortex (M1), area 4, arm area"

        # Standard NWB x/y/z: NMT v2.0-sym coordinates in PIR convention (microns).
        # When no atlas coordinates exist (Monkey L, pending), set to NaN.
        if has_acx:
            x_pir = -nmt_a * 1000.0  # +anterior -> +posterior, mm -> um
            y_pir = -nmt_s * 1000.0  # +superior -> +inferior, mm -> um
            z_pir = nmt_r * 1000.0   # +right stays +right, mm -> um
        else:
            x_pir = float("nan")
            y_pir = float("nan")
            z_pir = float("nan")

        # Add recording electrode with chamber grid coordinates
        nwbfile.add_electrode(
            x=x_pir,
            y=y_pir,
            z=z_pir,
            imp=float("nan"),  # Electrode impedance not recorded
            location=electrode_location,
            filtering="0.3-10kHz bandpass for spikes, 1-100Hz for LFP when available",
            group=recording_electrode_group,
            chamber_grid_ap_mm=-self.session_info["A_P"],
            chamber_grid_ml_mm=self.session_info["M_L"],
            chamber_insertion_depth_mm=self.session_info["Depth"],
        )

        # Add atlas coordinates via ndx-anatomical-localization if available
        if has_acx:
            # D99 space and coordinates table
            d99_space = Space(
                name="D99",
                space_name="D99",
                origin="anterior commissure",
                units="mm",
                orientation="RAS",
            )

            d99_coordinates_table = AnatomicalCoordinatesTable(
                name="D99AtlasCoordinates",
                target=nwbfile.electrodes,
                description=(
                    "Recording electrode coordinates in D99 macaque atlas space (RAS orientation, mm). "
                    "Origin: anterior commissure. "
                    "Coordinates computed by Dr. Robert Turner from chamber-relative positions using "
                    "the known chamber placement geometry (AP offset to AC and 35-degree coronal tilt). "
                    "See: https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/nonhuman/macaque_tempatl/atlas_d99v2.html"
                ),
                method=(
                    "Coordinates transformed from chamber-relative positions to D99 atlas space "
                    "by Dr. Robert Turner (data author) using a geometric transformation: "
                    "constant AP offset (-8.2 mm, chamber center to anterior commissure) "
                    "and 35-degree rotation in the coronal plane (coupling ML and Depth to atlas R and S axes). "
                    "No individual MRI registration was used."
                ),
                space=d99_space,
            )

            d99_coordinates_table.add_column(
                name="brain_region_id",
                description="D99 atlas region abbreviation (e.g. F1_(4), F2_(6DR/6DC), 3a/b)",
            )

            d99_coordinates_table.add_row(
                x=d99_r,
                y=d99_a,
                z=d99_s,
                localized_entity=0,  # Index into electrode table (single recording electrode)
                brain_region=d99_full_name,
                brain_region_id=d99_abbreviation,
            )

            localization = Localization()
            spaces_to_add = [d99_space]
            tables_to_add = [d99_coordinates_table]

            # NMT v2.0-sym space and coordinates table (via RheMAP nonlinear warp)
            nmt_space = Space(
                name="NMTv2sym",
                space_name="NMT_v2.0_sym",
                origin="ear bar zero",
                units="mm",
                orientation="RAS",
            )

            nmt_coordinates_table = AnatomicalCoordinatesTable(
                name="NMTv2symAtlasCoordinates",
                target=nwbfile.electrodes,
                description=(
                    "Recording electrode coordinates in NMT v2.0-sym (NIMH Macaque Template, symmetric) "
                    "atlas space (RAS orientation, mm). Origin: ear bar zero (EBZ). "
                    "Coordinates converted from D99 atlas space using a pre-computed nonlinear warp "
                    "from RheMAP (Sirmpilatze & Klink, 2020; DOI: 10.5281/zenodo.4748589). "
                    "See: https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/nonhuman/macaque_tempatl/template_nmtv2.html"
                ),
                method=(
                    "Coordinates first transformed from chamber-relative positions to D99 atlas space "
                    "by Dr. Robert Turner (geometric transformation: AP offset + 35-degree coronal rotation). "
                    "Then converted from D99 to NMT v2.0-sym using the pre-computed nonlinear composite warp "
                    "from RheMAP v1.3 (NMTv2.0-sym_to_D99_CompositeWarp.nii.gz, applied in reverse for points). "
                    "RAS-to-LPS conversion applied before ANTs warp, then reversed."
                ),
                space=nmt_space,
            )

            nmt_coordinates_table.add_column(
                name="brain_region_id",
                description="D99 atlas region abbreviation (looked up in D99 native space before warping)",
            )

            nmt_coordinates_table.add_row(
                x=nmt_r,
                y=nmt_a,
                z=nmt_s,
                localized_entity=0,
                brain_region=d99_full_name,
                brain_region_id=d99_abbreviation,
            )

            spaces_to_add.append(nmt_space)
            tables_to_add.append(nmt_coordinates_table)

            # MEBRAINS space and coordinates table (via RheMAP nonlinear warp)

            mebrains_space = Space(
                name="MEBRAINS",
                space_name="MEBRAINS_1.0",
                origin="anterior commissure",
                units="mm",
                orientation="RAS",
            )

            mebrains_coordinates_table = AnatomicalCoordinatesTable(
                name="MEBRAINSAtlasCoordinates",
                target=nwbfile.electrodes,
                description=(
                    "Recording electrode coordinates in MEBRAINS 1.0 (population-based macaque template) "
                    "atlas space (RAS orientation, mm). Origin: anterior commissure. "
                    "Coordinates converted from D99 atlas space using a pre-computed nonlinear warp "
                    "from RheMAP (G-NODE repository: https://gin.g-node.org/ChrisKlink/RheMAP). "
                    "See: https://doi.org/10.1162/imag_a_00077"
                ),
                method=(
                    "Coordinates first transformed from chamber-relative positions to D99 atlas space "
                    "by Dr. Robert Turner (geometric transformation: AP offset + 35-degree coronal rotation). "
                    "Then converted from D99 to MEBRAINS 1.0 using the pre-computed nonlinear composite warp "
                    "from RheMAP (MEBRAINS_to_D99_CompositeWarp.nii.gz, applied in reverse for points). "
                    "RAS-to-LPS conversion applied before ANTs warp, then reversed."
                ),
                space=mebrains_space,
            )

            mebrains_coordinates_table.add_column(
                name="brain_region_id",
                description="D99 atlas region abbreviation (looked up in D99 native space before warping)",
            )

            mebrains_coordinates_table.add_row(
                x=mebrains_r,
                y=mebrains_a,
                z=mebrains_s,
                localized_entity=0,
                brain_region=d99_full_name,
                brain_region_id=d99_abbreviation,
            )

            spaces_to_add.append(mebrains_space)
            tables_to_add.append(mebrains_coordinates_table)

            localization.add_spaces(spaces_to_add)
            # Add localization to the NWBFile before adding the coordinates tables,
            # so that both the DynamicTableRegion (localized_entity) and its target
            # (nwbfile.electrodes) share a common ancestor during validation.
            nwbfile.add_lab_meta_data(localization)
            localization.add_anatomical_coordinates_tables(tables_to_add)

        if self.verbose:
            print(f"Added electrode configuration: 1 recording electrode in electrodes table")
            if has_acx:
                print(f"Added D99 atlas coordinates (RAS mm): R={d99_r:.2f}, A={d99_a:.2f}, S={d99_s:.2f}")
                print(f"D99 region: {d99_full_name} ({d99_abbreviation})")
                print(f"Added NMT v2.0-sym coordinates (RAS mm): R={nmt_r:.2f}, A={nmt_a:.2f}, S={nmt_s:.2f}")
                print(f"Added MEBRAINS coordinates (RAS mm): R={mebrains_r:.2f}, A={mebrains_a:.2f}, S={mebrains_s:.2f}")