import logging
import math
from functools import lru_cache
from pathlib import Path
from typing import Optional

import nibabel as nib
import numpy as np
from scipy.spatial import cKDTree
import pandas as pd
from ndx_anatomical_localization import AnatomicalCoordinatesTable, D99v2Space, Localization, MEBRAINSSpace, NMTv2Space
from pydantic import FilePath
from pynwb import NWBFile

from neuroconv.basedatainterface import BaseDataInterface

logger = logging.getLogger(__name__)


def _to_float_or_nan(value) -> float:
    """Convert a value to float, returning NaN for non-numeric values like 'nt' or NaN."""
    try:
        result = float(value)
        return result
    except (ValueError, TypeError):
        return float("nan")


def _normalize_icms_effect(raw: str) -> str:
    """Normalize ICMS effect descriptions to consistent, expanded form.

    Expands abbreviations (ext. -> extension, flex. -> flexion, etc.),
    standardizes case, and maps special values (nt -> not_tested, nr -> no_response).
    """
    if pd.isna(raw) or raw == "":
        return ""
    raw = str(raw).strip()
    if raw.lower() in ("nt", "not tested"):
        return "not_tested"
    if raw.lower() in ("nr", "no response"):
        return "no_response"

    # Expand common abbreviations (order matters: longer patterns first)
    result = raw.lower()
    result = result.replace("ext. rotation", "external rotation")
    result = result.replace("rad. dev.", "radial deviation")
    result = result.replace("ulnar dev.", "ulnar deviation")
    result = result.replace("ext.", "extension")
    result = result.replace("flex.", "flexion")
    result = result.replace("abd.", "abduction")
    result = result.replace("sup.", "supination")
    # Handle forms without trailing periods (word boundaries via space or end-of-string)
    import re
    result = re.sub(r"\bext\b", "extension", result)
    result = re.sub(r"\bflex\b", "flexion", result)
    result = re.sub(r"\badduct\b", "adduction", result)
    return result

_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent.parent

# D99 atlas data directory (relative to project root).
# Required files (download from https://afni.nimh.nih.gov/pub/dist/atlases/macaque/d99/D99_v2.0_dist.tgz):
#   - D99_atlas_v2.0.nii.gz  (813K, parcellation volume)
#   - D99_v2.0_labels_semicolon.txt  (20K, label names)
# Extract to: <project_root>/data/d99_atlas/D99_v2.0_dist/
_D99_ATLAS_DIR = _PROJECT_ROOT / "data" / "d99_atlas" / "D99_v2.0_dist"

# RheMAP warp file for D99 -> NMT v2.0-sym coordinate conversion.
# Download from https://zenodo.org/records/4748589 (warps_final_NMTv2.0-sym.zip).
# For point transforms, the warp direction is REVERSED: use the NMTv2.0-sym_to_D99 warp
# to move a point FROM D99 TO NMT v2.0-sym (ANTs convention).
_RHEMAP_WARP_PATH = _PROJECT_ROOT / "data" / "rhemap_warps" / "NMTv2.0-sym_to_D99_CompositeWarp.nii.gz"

# RheMAP warp file for D99 -> MEBRAINS coordinate conversion.
# Download from https://gin.g-node.org/ChrisKlink/RheMAP (warps/final/).
# Same reversed-direction ANTs convention as the NMT warp above.
_MEBRAINS_WARP_PATH = _PROJECT_ROOT / "data" / "rhemap_warps" / "MEBRAINS_to_D99_CompositeWarp.nii.gz"

# MEBRAINS atlas data directory (relative to project root).
# Required files:
#   - MEBRAINS_parcellation.nii.gz  (parcellation volume)
#   - MEBRAINS_labels.json  (label ID -> region name mapping)
_MEBRAINS_ATLAS_DIR = _PROJECT_ROOT / "data" / "mebrains"

# Precomputed warp results (CSV). Generated by scripts/precompute_warped_coordinates.py.
# Contains D99 -> NMT and D99 -> MEBRAINS coordinates for all unique electrode positions.
# This avoids calling ANTs at conversion time (~3s per warp, ~30 min for 358 sessions).
_WARPED_COORDS_PATH = (
    _PROJECT_ROOT / "src" / "turner_lab_to_nwb" / "asap_m1_mptp"
    / "assets" / "metadata_table" / "warped_coordinates.csv"
)

# CHARM level 4 atlas on NMT v2.0-sym (for M1 region lookup in NMT space).
# CHARM is the native hierarchical parcellation for NMT. Level 4 is the first level
# where M1 (primary_motor_cortex, index 79) is separated from premotor and SMA.
_CHARM_ATLAS_PATH = (
    _PROJECT_ROOT / "data" / "nmt_v2" / "NMT_v2.0_sym" / "NMT_v2.0_sym"
    / "supplemental_CHARM" / "CHARM_4_in_NMT_v2.0_sym.nii.gz"
)
_CHARM_KEY_PATH = (
    _PROJECT_ROOT / "data" / "nmt_v2" / "NMT_v2.0_sym"
    / "tables_CHARM" / "CHARM_key_4.txt"
)

# M1-constrained nearest-neighbor parameters.
_MAX_NEAREST_MM = 5.0
_D99_M1_INDEX = 359  # D99 label id for F1_(4), agranular frontal area F1 (= area 4, primary motor cortex).
_CHARM_M1_INDEX = 79  # CHARM level-4 label id for M1 (primary motor cortex). M1 is a single label at every CHARM level.
_MEBRAINS_M1_LABELS = {301: "4a left", 303: "4p left"}  # Julich Brain subdivisions of primary motor cortex (left hemisphere).


@lru_cache(maxsize=1)
def _load_d99_atlas() -> tuple[np.ndarray, np.ndarray, dict]:
    """Load D99 atlas data (cached across sessions).

    Returns
    -------
    atlas_data : np.ndarray
        3D array of label IDs
    inv_affine : np.ndarray
        Inverse affine matrix (world RAS mm -> voxel indices)
    labels : dict
        Mapping from label_id to {"abbreviation": str, "full_name": str}
    """
    atlas_path = _D99_ATLAS_DIR / "D99_atlas_v2.0.nii.gz"
    labels_path = _D99_ATLAS_DIR / "D99_v2.0_labels_semicolon.txt"

    atlas = nib.load(str(atlas_path))
    atlas_data = np.asarray(atlas.dataobj)
    inv_affine = np.linalg.inv(atlas.affine)

    # Parse label file: id;abbreviation;full_name[;category;subcategory]
    labels = {}
    with open(labels_path) as f:
        for line in f:
            parts = line.strip().split(";")
            if len(parts) >= 3:
                label_id = int(parts[0])
                abbreviation = parts[1].strip()
                full_name = parts[2].strip().strip('"')
                labels[label_id] = {"abbreviation": abbreviation, "full_name": full_name}

    return atlas_data, inv_affine, labels


@lru_cache(maxsize=1)
def _load_mebrains_atlas() -> tuple[np.ndarray, np.ndarray, dict]:
    """Load MEBRAINS atlas data (cached across sessions).

    Returns
    -------
    atlas_data : np.ndarray
        3D array of label IDs
    inv_affine : np.ndarray
        Inverse affine matrix (world RAS mm -> voxel indices)
    labels : dict
        Mapping from label_id to {"name": str}
    """
    import json

    atlas_path = _MEBRAINS_ATLAS_DIR / "MEBRAINS_parcellation.nii.gz"
    labels_path = _MEBRAINS_ATLAS_DIR / "MEBRAINS_labels.json"

    atlas = nib.load(str(atlas_path))
    atlas_data = np.asarray(atlas.dataobj)
    inv_affine = np.linalg.inv(atlas.affine)

    with open(labels_path) as f:
        raw_labels = json.load(f)
    labels = {int(k): {"name": v} for k, v in raw_labels.items()}

    return atlas_data, inv_affine, labels


@lru_cache(maxsize=1)
def _load_charm_m1_tree():
    """Load CHARM level 4 atlas and build KD-tree of M1 voxels in world RAS mm (cached).

    Returns
    -------
    m1_tree : cKDTree
        KD-tree of M1 voxel positions in NMT RAS world coordinates (mm).
    atlas_data : np.ndarray
        3D array of CHARM label IDs.
    inv_affine : np.ndarray
        Inverse affine (world RAS mm -> voxel indices).
    """
    atlas = nib.load(str(_CHARM_ATLAS_PATH))
    atlas_data = np.asarray(atlas.dataobj)
    affine = atlas.affine
    inv_affine = np.linalg.inv(affine)

    m1_voxels = np.argwhere(atlas_data == _CHARM_M1_INDEX)
    m1_world_coords = nib.affines.apply_affine(affine, m1_voxels)
    m1_tree = cKDTree(m1_world_coords)

    return m1_tree, atlas_data, inv_affine


@lru_cache(maxsize=1)
def _load_charm_labels() -> dict:
    """Parse the CHARM level-4 key file into {index: (abbreviation, full_name)} (cached).

    The key file is tab-separated with a header row:
        Index  Abbreviation  Full_Name  First_Level  Last_Level
    """
    labels: dict[int, tuple[str, str]] = {}
    with open(_CHARM_KEY_PATH) as f:
        header = f.readline()  # discard header
        del header
        for line in f:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 3:
                continue
            try:
                index = int(parts[0])
            except ValueError:
                continue
            abbreviation = parts[1].strip()
            full_name = parts[2].strip()
            labels[index] = (abbreviation, full_name)
    return labels


def lookup_nmt_voxel(nmt_r: float, nmt_a: float, nmt_s: float) -> tuple[str, str]:
    """Look up the raw CHARM level-4 voxel label at an NMT RAS coordinate.

    This is the honest, direct atlas answer with no interpolation. For the M1-curated
    label used on the map, see :func:`lookup_charm_m1`.

    Parameters
    ----------
    nmt_r, nmt_a, nmt_s : float
        NMT v2.0-sym RAS coordinates (mm).

    Returns
    -------
    voxel_label : str
        CHARM level-4 full name (e.g. "primary_motor_cortex", "primary_somatosensory_cortex")
        when the voxel carries a labeled region; "unlabeled voxel (label=0)" when in-volume
        label=0; "outside template volume" when out-of-bounds.
    voxel_label_id : str
        CHARM abbreviation (e.g. "M1", "SI") when labeled; "unlabeled" when in-volume
        label=0; "outside_volume" when out-of-bounds.
    """
    _, atlas_data, inv_affine = _load_charm_m1_tree()  # reuses cached atlas data
    labels = _load_charm_labels()

    world_coord = np.array([nmt_r, nmt_a, nmt_s])
    voxel = np.round(nib.affines.apply_affine(inv_affine, world_coord)).astype(int)

    if not all(0 <= voxel[i] < atlas_data.shape[i] for i in range(3)):
        return "outside template volume", "outside_volume"

    label_id = int(atlas_data[tuple(voxel)])
    if label_id > 0 and label_id in labels:
        abbreviation, full_name = labels[label_id]
        return full_name, abbreviation

    return "unlabeled voxel (label=0)", "unlabeled"


@lru_cache(maxsize=1)
def _load_mebrains_m1_tree():
    """Build KD-tree of MEBRAINS M1 voxels (4a + 4p) in world RAS mm (cached).

    Reuses atlas data from _load_mebrains_atlas().

    Returns
    -------
    m1_tree : cKDTree
        KD-tree of M1 voxel positions in MEBRAINS RAS world coordinates (mm).
    m1_voxels : np.ndarray
        (N, 3) array of M1 voxel indices (for label lookup after query).
    """
    atlas_data, inv_affine, _ = _load_mebrains_atlas()
    affine = np.linalg.inv(inv_affine)

    m1_mask = np.isin(atlas_data, list(_MEBRAINS_M1_LABELS.keys()))
    m1_voxels = np.argwhere(m1_mask)
    m1_world_coords = nib.affines.apply_affine(affine, m1_voxels)
    m1_tree = cKDTree(m1_world_coords)

    return m1_tree, m1_voxels


@lru_cache(maxsize=1)
def _load_d99_m1_tree():
    """Build a KD-tree of D99 F1_(4) voxel world coordinates (cached).

    Returns
    -------
    m1_tree : cKDTree
        KD-tree of F1_(4) voxel positions in D99 RAS world coordinates (mm).
    atlas_data : np.ndarray
        3D array of D99 label IDs.
    inv_affine : np.ndarray
        Inverse affine (world RAS mm -> voxel indices).
    """
    atlas_data, inv_affine, _ = _load_d99_atlas()
    affine = np.linalg.inv(inv_affine)

    m1_voxels = np.argwhere(atlas_data == _D99_M1_INDEX)
    m1_world_coords = nib.affines.apply_affine(affine, m1_voxels)
    m1_tree = cKDTree(m1_world_coords)

    return m1_tree, atlas_data, inv_affine


def lookup_d99_m1(ap_acx: float, ml_acx: float, depth_acx: float) -> tuple[str, str, str, float]:
    """Look up D99 F1_(4) for a chamber-relative ACx coordinate, with M1-constrained nearest-neighbor.

    Parameters
    ----------
    ap_acx : float
        Anterior-posterior coordinate (+anterior, mm).
    ml_acx : float
        Medial-lateral coordinate (+lateral left, mm).
    depth_acx : float
        Depth coordinate (+superior/dorsal, mm).

    Returns
    -------
    region_name : str
        "agranular frontal area F1 (or area 4)" if within the 5 mm distance cap, else "outside atlas".
    region_id : str
        "F1_(4)" if within the 5 mm distance cap, else "outside".
    method : str
        "exact", "nearest_neighbor", or "no_m1_within_5mm".
    distance_mm : float
        0.0 for exact, Euclidean distance for nearest_neighbor, NaN for no_m1_within_5mm.
    """
    m1_tree, atlas_data, inv_affine = _load_d99_m1_tree()

    # ACx -> D99 RAS world (AC is at origin; left hemisphere = negative R).
    r = -ml_acx
    a = ap_acx
    s = depth_acx
    world_coord = np.array([r, a, s])
    voxel = np.round(nib.affines.apply_affine(inv_affine, world_coord)).astype(int)

    if all(0 <= voxel[i] < atlas_data.shape[i] for i in range(3)):
        label_id = int(atlas_data[tuple(voxel)])
        if label_id == _D99_M1_INDEX:
            return "agranular frontal area F1 (or area 4)", "F1_(4)", "exact", 0.0

    dist_mm, _ = m1_tree.query(world_coord)
    if dist_mm <= _MAX_NEAREST_MM:
        return "agranular frontal area F1 (or area 4)", "F1_(4)", "nearest_neighbor", round(float(dist_mm), 4)

    return "outside atlas", "outside", "no_m1_within_5mm", float("nan")


def snap_d99_to_f1_voxel(d99_r: float, d99_a: float, d99_s: float) -> tuple[float, float, float, bool]:
    """Snap a D99 RAS coordinate to the nearest F1_(4) voxel center, within a 5 mm cap.

    The curation is done in D99 space (the author's canonical frame). Downstream NMT and
    MEBRAINS curated coordinates are obtained by warping this curated D99 coordinate
    through the same RheMAP transforms used for the raw coordinates.

    Parameters
    ----------
    d99_r, d99_a, d99_s : float
        Raw D99 RAS coordinates (mm), typically from the author's geometric transform.

    Returns
    -------
    r_curated, a_curated, s_curated : float
        D99 RAS world coordinates (mm) of the nearest F1_(4) voxel center if within the
        5 mm cap; otherwise the input (r, a, s) unchanged.
    snapped : bool
        True if a snap was applied, False if the input was beyond the cap (no snap).
    """
    m1_tree, _, _ = _load_d99_m1_tree()
    world_coord = np.array([d99_r, d99_a, d99_s])
    dist_mm, idx = m1_tree.query(world_coord)
    if dist_mm > _MAX_NEAREST_MM:
        return d99_r, d99_a, d99_s, False
    # cKDTree.data holds the exact world-coord array we indexed with.
    nearest = m1_tree.data[idx]
    return float(nearest[0]), float(nearest[1]), float(nearest[2]), True


def lookup_charm_m1(nmt_r: float, nmt_a: float, nmt_s: float) -> tuple[str, str, str, float]:
    """Look up CHARM M1 region for an NMT RAS coordinate, with M1-constrained nearest-neighbor.

    Parameters
    ----------
    nmt_r, nmt_a, nmt_s : float
        NMT v2.0-sym RAS coordinates (mm).

    Returns
    -------
    region_name : str
        "primary_motor_cortex" if within the 5 mm distance cap, else "outside atlas".
    region_id : str
        "M1" if within the 5 mm distance cap, else "outside".
    method : str
        "exact", "nearest_neighbor", or "no_m1_within_5mm".
    distance_mm : float
        0.0 for exact, Euclidean distance for nearest_neighbor, NaN for no_m1_within_5mm.
    """
    m1_tree, atlas_data, inv_affine = _load_charm_m1_tree()

    world_coord = np.array([nmt_r, nmt_a, nmt_s])
    voxel = np.round(nib.affines.apply_affine(inv_affine, world_coord)).astype(int)

    if all(0 <= voxel[i] < atlas_data.shape[i] for i in range(3)):
        label_id = int(atlas_data[tuple(voxel)])
        if label_id == _CHARM_M1_INDEX:
            return "primary_motor_cortex", "M1", "exact", 0.0

    dist_mm, _ = m1_tree.query(world_coord)
    if dist_mm <= _MAX_NEAREST_MM:
        return "primary_motor_cortex", "M1", "nearest_neighbor", round(float(dist_mm), 4)

    return "outside atlas", "outside", "no_m1_within_5mm", float("nan")


def lookup_mebrains_m1(mebrains_r: float, mebrains_a: float, mebrains_s: float) -> tuple[str, str, str, float]:
    """Look up MEBRAINS M1 subdivision for a MEBRAINS RAS coordinate, with M1-constrained nearest-neighbor.

    Parameters
    ----------
    mebrains_r, mebrains_a, mebrains_s : float
        MEBRAINS RAS coordinates (mm).

    Returns
    -------
    region_name : str
        "4a left" or "4p left" if within the 5 mm distance cap, else "outside atlas".
    region_id : str
        "301" or "303" if within the 5 mm distance cap, else "outside".
    method : str
        "exact", "nearest_neighbor", or "no_m1_within_5mm".
    distance_mm : float
        0.0 for exact, Euclidean distance for nearest_neighbor, NaN for no_m1_within_5mm.
    """
    atlas_data, inv_affine, _ = _load_mebrains_atlas()
    m1_tree, m1_voxels = _load_mebrains_m1_tree()

    world_coord = np.array([mebrains_r, mebrains_a, mebrains_s])
    voxel = np.round(nib.affines.apply_affine(inv_affine, world_coord)).astype(int)

    if all(0 <= voxel[i] < atlas_data.shape[i] for i in range(3)):
        label_id = int(atlas_data[tuple(voxel)])
        if label_id in _MEBRAINS_M1_LABELS:
            return _MEBRAINS_M1_LABELS[label_id], str(label_id), "exact", 0.0

    dist_mm, idx = m1_tree.query(world_coord)
    if dist_mm <= _MAX_NEAREST_MM:
        nearest_voxel = tuple(m1_voxels[idx])
        nearest_id = int(atlas_data[nearest_voxel])
        return _MEBRAINS_M1_LABELS[nearest_id], str(nearest_id), "nearest_neighbor", round(float(dist_mm), 4)

    return "outside atlas", "outside", "no_m1_within_5mm", float("nan")


def lookup_mebrains_region(mebrains_r: float, mebrains_a: float, mebrains_s: float) -> tuple[str, str]:
    """Look up the raw MEBRAINS atlas voxel label at a MEBRAINS RAS coordinate.

    This is the honest, direct atlas answer with no interpolation. For the M1-curated
    label used on the map, see :func:`lookup_mebrains_m1`.

    Parameters
    ----------
    mebrains_r : float
        Right coordinate in MEBRAINS RAS (mm).
    mebrains_a : float
        Anterior coordinate in MEBRAINS RAS (mm).
    mebrains_s : float
        Superior coordinate in MEBRAINS RAS (mm).

    Returns
    -------
    voxel_label : str
        Region full-name from the MEBRAINS label table (e.g., "4p left") when the
        voxel carries a labeled region; the literal string "unlabeled voxel (label=0)"
        when the coord falls on an unlabeled voxel inside the template; the literal
        string "outside template volume" when the coord falls outside the template
        bounding box.
    voxel_label_id : str
        Numeric string form of the MEBRAINS label ID (e.g. "303") when labeled;
        the literal string "unlabeled" when in-volume label=0; the literal string
        "outside_volume" when out-of-bounds.
    """
    atlas_data, inv_affine, labels = _load_mebrains_atlas()

    world_coord = np.array([mebrains_r, mebrains_a, mebrains_s])
    voxel = nib.affines.apply_affine(inv_affine, world_coord)
    voxel_idx = tuple(np.round(voxel).astype(int))

    if not all(0 <= voxel_idx[i] < atlas_data.shape[i] for i in range(3)):
        return "outside template volume", "outside_volume"

    label_id = int(atlas_data[voxel_idx])
    if label_id > 0 and label_id in labels:
        return labels[label_id]["name"], str(label_id)

    return "unlabeled voxel (label=0)", "unlabeled"


@lru_cache(maxsize=1)
def _load_warped_coordinates():
    """Load precomputed warped coordinates CSV (cached across sessions).

    Returns a dict mapping (d99_r, d99_a, d99_s) rounded keys to a 15-tuple of
    (nmt_r, nmt_a, nmt_s, mebrains_r, mebrains_a, mebrains_s,
     d99_r_c, d99_a_c, d99_s_c, nmt_r_c, nmt_a_c, nmt_s_c,
     mebrains_r_c, mebrains_a_c, mebrains_s_c).
    The _c suffix marks curated values: curated D99 is the nearest F1_(4) voxel center
    within 5 mm; curated NMT / MEBRAINS are the RheMAP warps of that curated D99 point.
    """
    import pandas as pd

    if not _WARPED_COORDS_PATH.exists():
        raise FileNotFoundError(
            f"Precomputed warp file not found at {_WARPED_COORDS_PATH}. "
            "Run: uv run python src/turner_lab_to_nwb/asap_m1_mptp/scripts/precompute_warped_coordinates.py"
        )

    df = pd.read_csv(_WARPED_COORDS_PATH)
    lookup = {}
    for _, row in df.iterrows():
        key = (round(row["d99_r"], 6), round(row["d99_a"], 6), round(row["d99_s"], 6))
        lookup[key] = (
            row["nmt_r"], row["nmt_a"], row["nmt_s"],
            row["mebrains_r"], row["mebrains_a"], row["mebrains_s"],
            row["d99_r_c"], row["d99_a_c"], row["d99_s_c"],
            row["nmt_r_c"], row["nmt_a_c"], row["nmt_s_c"],
            row["mebrains_r_c"], row["mebrains_a_c"], row["mebrains_s_c"],
        )
    return lookup


def lookup_warped_coordinates(
    d99_r: float, d99_a: float, d99_s: float
) -> tuple[float, float, float, float, float, float,
           float, float, float, float, float, float, float, float, float]:
    """Look up precomputed NMT and MEBRAINS coordinates (raw + curated) for a D99 RAS position.

    Parameters
    ----------
    d99_r, d99_a, d99_s : float
        Raw D99 RAS coordinates (mm), typically from the author's geometric transform.

    Returns
    -------
    Tuple of 15 floats in order:
        (nmt_r, nmt_a, nmt_s,
         mebrains_r, mebrains_a, mebrains_s,
         d99_r_c, d99_a_c, d99_s_c,
         nmt_r_c, nmt_a_c, nmt_s_c,
         mebrains_r_c, mebrains_a_c, mebrains_s_c).
    The unsuffixed coordinates are the raw RheMAP warp outputs of the input D99 coord;
    the _c suffix marks curated values (nearest F1_(4) voxel in D99, then warped).

    Raises
    ------
    KeyError
        If the coordinate is not in the precomputed table. Regenerate with:
        uv run python src/turner_lab_to_nwb/asap_m1_mptp/scripts/precompute_warped_coordinates.py
    """
    lookup = _load_warped_coordinates()
    key = (round(d99_r, 6), round(d99_a, 6), round(d99_s, 6))
    if key not in lookup:
        raise KeyError(
            f"D99 coordinate ({d99_r}, {d99_a}, {d99_s}) not found in precomputed warp table. "
            "Regenerate with: uv run python src/turner_lab_to_nwb/asap_m1_mptp/scripts/precompute_warped_coordinates.py"
        )
    return lookup[key]


def lookup_d99_region(ap_acx: float, ml_acx: float, depth_acx: float) -> tuple[str, str]:
    """Look up the raw D99 atlas voxel label at a chamber-relative ACx coordinate.

    This is the honest, direct atlas answer with no interpolation. For the M1-curated
    label used on the map, see :func:`lookup_d99_m1`.

    Parameters
    ----------
    ap_acx : float
        Anterior-posterior coordinate (+anterior, mm).
    ml_acx : float
        Medial-lateral coordinate (+lateral left, mm).
    depth_acx : float
        Depth coordinate (+superior/dorsal, mm).

    Returns
    -------
    voxel_label : str
        Full region name from the D99 label table when the voxel carries a labeled
        region; "unlabeled voxel (label=0)" when in-volume label=0; "outside template
        volume" when out-of-bounds.
    voxel_label_id : str
        D99 abbreviation (e.g. "F1_(4)", "area_1-2") when labeled; "unlabeled" when
        in-volume label=0; "outside_volume" when out-of-bounds.
    """
    atlas_data, inv_affine, labels = _load_d99_atlas()

    # Convert ACx to D99 RAS world coordinates (AC is at origin 0,0,0)
    r = -ml_acx  # left hemisphere = negative R
    a = ap_acx
    s = depth_acx

    world_coord = np.array([r, a, s])
    voxel = nib.affines.apply_affine(inv_affine, world_coord)
    voxel_idx = tuple(np.round(voxel).astype(int))

    if not all(0 <= voxel_idx[i] < atlas_data.shape[i] for i in range(3)):
        return "outside template volume", "outside_volume"

    label_id = int(atlas_data[voxel_idx])
    if label_id > 0 and label_id in labels:
        return labels[label_id]["full_name"], labels[label_id]["abbreviation"]

    return "unlabeled voxel (label=0)", "unlabeled"


def convert_d99_to_nmt(r_d99: float, a_d99: float, s_d99: float) -> tuple[float, float, float]:
    """Convert a D99 RAS coordinate (mm) to NMT v2.0-sym RAS (mm) using a RheMAP warp.

    Uses the pre-computed nonlinear warp from RheMAP (Sirmpilatze & Klink, 2020).
    ANTs operates in LPS+ internally, so RAS coordinates are converted to LPS before
    applying the warp and converted back afterward. For point transforms, the warp
    direction is reversed: the NMTv2.0-sym_to_D99 warp moves points FROM D99 TO NMT.

    Parameters
    ----------
    r_d99 : float
        Right coordinate in D99 RAS (mm)
    a_d99 : float
        Anterior coordinate in D99 RAS (mm)
    s_d99 : float
        Superior coordinate in D99 RAS (mm)

    Returns
    -------
    tuple of (r_nmt, a_nmt, s_nmt) in NMT v2.0-sym RAS (mm).

    Raises
    ------
    FileNotFoundError
        If the RheMAP warp file is not found.
    """
    if not _RHEMAP_WARP_PATH.exists():
        raise FileNotFoundError(
            f"RheMAP warp file not found at {_RHEMAP_WARP_PATH}. "
            "Download warps_final_NMTv2.0-sym.zip from https://zenodo.org/records/4748589 "
            "and extract NMTv2.0-sym_to_D99_CompositeWarp.nii.gz to data/rhemap_warps/"
        )

    import ants
    import pandas as pd

    # RAS to LPS (negate R and A)
    l_d99 = -r_d99
    p_d99 = -a_d99
    s_lps = s_d99

    points = pd.DataFrame({"x": [l_d99], "y": [p_d99], "z": [s_lps]})

    transformed = ants.apply_transforms_to_points(
        dim=3,
        points=points,
        transformlist=[str(_RHEMAP_WARP_PATH)],
    )

    # LPS back to RAS (negate L and P)
    r_nmt = -transformed["x"].values[0]
    a_nmt = -transformed["y"].values[0]
    s_nmt = transformed["z"].values[0]

    return (float(r_nmt), float(a_nmt), float(s_nmt))


def batch_convert_d99_to_nmt(
    r_d99: np.ndarray, a_d99: np.ndarray, s_d99: np.ndarray
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Convert multiple D99 RAS coordinates to NMT v2.0-sym RAS in a single warp call.

    Same as convert_d99_to_nmt but processes all coordinates at once, which is
    much faster (~3s total vs ~3s per coordinate) since the warp field is loaded once.

    Parameters
    ----------
    r_d99, a_d99, s_d99 : np.ndarray
        Arrays of D99 RAS coordinates (mm)

    Returns
    -------
    tuple of (r_nmt, a_nmt, s_nmt) arrays in NMT v2.0-sym RAS (mm).

    Raises
    ------
    FileNotFoundError
        If the RheMAP warp file is not found.
    """
    if not _RHEMAP_WARP_PATH.exists():
        raise FileNotFoundError(
            f"RheMAP warp file not found at {_RHEMAP_WARP_PATH}. "
            "Download warps_final_NMTv2.0-sym.zip from https://zenodo.org/records/4748589 "
            "and extract NMTv2.0-sym_to_D99_CompositeWarp.nii.gz to data/rhemap_warps/"
        )

    import ants
    import pandas as pd

    points = pd.DataFrame({"x": -np.asarray(r_d99), "y": -np.asarray(a_d99), "z": np.asarray(s_d99)})
    transformed = ants.apply_transforms_to_points(dim=3, points=points, transformlist=[str(_RHEMAP_WARP_PATH)])
    return (-transformed["x"].values, -transformed["y"].values, transformed["z"].values)


def convert_d99_to_mebrains(r_d99: float, a_d99: float, s_d99: float) -> tuple[float, float, float]:
    """Convert a D99 RAS coordinate (mm) to MEBRAINS RAS (mm) using a RheMAP warp.

    Uses the pre-computed nonlinear warp from RheMAP (G-NODE repository).
    Same RAS/LPS and reversed-direction conventions as convert_d99_to_nmt.

    Parameters
    ----------
    r_d99 : float
        Right coordinate in D99 RAS (mm)
    a_d99 : float
        Anterior coordinate in D99 RAS (mm)
    s_d99 : float
        Superior coordinate in D99 RAS (mm)

    Returns
    -------
    tuple of (r, a, s) in MEBRAINS RAS (mm).

    Raises
    ------
    FileNotFoundError
        If the RheMAP warp file is not found.
    """
    if not _MEBRAINS_WARP_PATH.exists():
        raise FileNotFoundError(
            f"RheMAP warp file not found at {_MEBRAINS_WARP_PATH}. "
            "Download from https://gin.g-node.org/ChrisKlink/RheMAP (warps/final/) "
            "and place MEBRAINS_to_D99_CompositeWarp.nii.gz in data/rhemap_warps/"
        )

    import ants
    import pandas as pd

    # RAS to LPS (negate R and A)
    points = pd.DataFrame({"x": [-r_d99], "y": [-a_d99], "z": [s_d99]})

    transformed = ants.apply_transforms_to_points(
        dim=3,
        points=points,
        transformlist=[str(_MEBRAINS_WARP_PATH)],
    )

    # LPS back to RAS (negate L and P)
    r_mebrains = -transformed["x"].values[0]
    a_mebrains = -transformed["y"].values[0]
    s_mebrains = transformed["z"].values[0]

    return (float(r_mebrains), float(a_mebrains), float(s_mebrains))


def batch_convert_d99_to_mebrains(
    r_d99: np.ndarray, a_d99: np.ndarray, s_d99: np.ndarray
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Convert multiple D99 RAS coordinates to MEBRAINS RAS in a single warp call.

    Same as convert_d99_to_mebrains but processes all coordinates at once.

    Parameters
    ----------
    r_d99, a_d99, s_d99 : np.ndarray
        Arrays of D99 RAS coordinates (mm)

    Returns
    -------
    tuple of (r, a, s) arrays in MEBRAINS RAS (mm).

    Raises
    ------
    FileNotFoundError
        If the RheMAP warp file is not found.
    """
    if not _MEBRAINS_WARP_PATH.exists():
        raise FileNotFoundError(
            f"RheMAP warp file not found at {_MEBRAINS_WARP_PATH}. "
            "Download from https://gin.g-node.org/ChrisKlink/RheMAP (warps/final/) "
            "and place MEBRAINS_to_D99_CompositeWarp.nii.gz in data/rhemap_warps/"
        )

    import ants
    import pandas as pd

    points = pd.DataFrame({"x": -np.asarray(r_d99), "y": -np.asarray(a_d99), "z": np.asarray(s_d99)})
    transformed = ants.apply_transforms_to_points(dim=3, points=points, transformlist=[str(_MEBRAINS_WARP_PATH)])
    return (-transformed["x"].values, -transformed["y"].values, transformed["z"].values)


class M1MPTPElectrodesInterface(BaseDataInterface):
    """Data interface for Turner Lab M1 MPTP electrode setup (recording and stimulation electrodes)."""

    keywords = ("electrodes", "recording electrodes", "stimulation electrodes", "antidromic identification")
    associated_suffixes = (".mat",)
    info = "Interface for Turner Lab M1 MPTP electrode configuration including recording and stimulation electrodes"

    def __init__(
        self,
        file_path: FilePath,
        session_metadata: dict,
        verbose: bool = False,
    ):
        """
        Initialize the M1MPTPElectrodesInterface.

        Parameters
        ----------
        file_path : FilePath
            Path to the first Turner Lab .mat file (used for session metadata extraction)
        session_metadata : dict
            Metadata for all units in this session (each unit contains session-level info)
        verbose : bool, optional
            Whether to print verbose output, by default False
        """
        super().__init__(verbose=verbose)
        self.base_file_path = Path(file_path)
        self.session_metadata = session_metadata
        
        # Extract session-level info from first unit (all units have same session info)
        if self.session_metadata:
            first_unit = self.session_metadata[0]
            self.session_info = {
                "Animal": first_unit["Animal"],
                "MPTP": first_unit["MPTP"],
                "DateCollected": first_unit["DateCollected"],
                "A_P": first_unit["A_P"],
                "M_L": first_unit["M_L"],
                "Depth": first_unit["Depth"],
                "A_P_acx": first_unit.get("A_P_acx", float("nan")),
                "M_L_acx": first_unit.get("M_L_acx", float("nan")),
                "Depth_acx": first_unit.get("Depth_acx", float("nan")),
                "Microstim_Effect": first_unit.get("Microstim_Effect", first_unit.get("Microtim_Effect", "")),
                "Microstim_Threshold": first_unit.get("Microstim_Threshold", float("nan")),
            }

    def add_to_nwbfile(self, nwbfile: NWBFile, metadata: Optional[dict] = None) -> None:
        """
        Add electrode configuration to the NWB file.

        Parameters
        ----------
        nwbfile : NWBFile
            The NWB file object to add electrode configuration to
        metadata : dict, optional
            Metadata dictionary
        """
        if metadata is None:
            metadata = self.get_metadata()

        # Create device for M1 recording electrode
        recording_device = nwbfile.create_device(
            name="DeviceMicroelectrodeRecording",
            description="Glass-coated PtIr microelectrode mounted in hydraulic microdrive (MO-95, Narishige Intl., Tokyo). "
            "Signal amplified 10^4, bandpass filtered 0.3-10kHz. Sampling: 20kHz for unit discrimination.",
        )

        # Create devices for chronically implanted stimulation electrodes
        # These are documented as devices even though they're not in the electrodes table
        # (stimulation electrode metadata is in StimulationElectrodesTable in the antidromic_identification module)
        nwbfile.create_device(
            name="DeviceMicrowirePeduncleStimulation",
            description="Custom-built PtIr microwire electrode for antidromic stimulation in cerebral peduncle. "
            "Chronically implanted for PTN identification.",
        )
        nwbfile.create_device(
            name="DeviceMicrowirePutamenStimulation1",
            description="Custom-built PtIr microwire electrode 1 of 3 for antidromic stimulation in posterolateral putamen. "
            "Chronically implanted for CSN identification.",
        )
        nwbfile.create_device(
            name="DeviceMicrowirePutamenStimulation2",
            description="Custom-built PtIr microwire electrode 2 of 3 for antidromic stimulation in posterolateral putamen. "
            "Chronically implanted for CSN identification.",
        )
        nwbfile.create_device(
            name="DeviceMicrowirePutamenStimulation3",
            description="Custom-built PtIr microwire electrode 3 of 3 for antidromic stimulation in posterolateral putamen. "
            "Chronically implanted for CSN identification.",
        )
        nwbfile.create_device(
            name="DeviceMicrowireThalamicStimulation",
            description="Custom-built PtIr microwire electrode for antidromic stimulation in VL thalamus. "
            "Chronically implanted for thalamocortical projection identification.",
        )
        nwbfile.create_device(
            name="DeviceMicrowireSTNStimulation",
            description="Custom-built PtIr microwire electrode for antidromic stimulation in subthalamic nucleus (STN). "
            "Chronically implanted for STN projection identification.",
        )

        # Recording electrode group for M1 chamber (left hemisphere)
        recording_electrode_group = nwbfile.create_electrode_group(
            name="ElectrodeGroupMicroelectrodeRecording",
            description="Left primary motor cortex recording within chamber-relative coordinate system. "
            "Chamber surgically positioned over left M1. Daily positions relative to chamber center. "
            "Functional verification via microstimulation (≤40μA, 10 pulses at 300Hz).",
            location="Primary motor cortex (M1), area 4, arm area",
            device=recording_device,
        )

        # Add custom columns for chamber grid coordinates and recording system metadata
        nwbfile.add_electrode_column(
            name="chamber_grid_ap_mm",
            description=(
                "Chamber grid position along the anterior-posterior axis, relative to chamber center "
                "(mm, positive = posterior). Recordings span -7 to 0 mm (all anterior to chamber center). "
                "NaN for stimulation electrodes."
            ),
        )
        nwbfile.add_electrode_column(
            name="chamber_grid_ml_mm",
            description=(
                "Chamber grid position along the medial-lateral axis, relative to chamber center "
                "(mm, positive = right). Recordings span -6 to -2 mm (all in left hemisphere). "
                "NaN for stimulation electrodes."
            ),
        )
        nwbfile.add_electrode_column(
            name="chamber_insertion_depth_mm",
            description=(
                "Electrode insertion depth from chamber reference point "
                "(mm, positive = deeper, range: 8.4-27.6mm). NaN for stimulation electrodes."
            ),
        )
        nwbfile.add_electrode_column(
            name="icms_effect",
            description=(
                "Movement evoked by intracortical microstimulation (ICMS) at recording site "
                "(10 biphasic pulses at 300 Hz, typically at or below 20 uA). "
                "Microexcitability at low currents is a hallmark of primary motor cortex. "
                "Values: movement description (e.g. 'wrist ext.', 'finger flex'), "
                "'NT' (not tested), 'NR'/'nr' (no response)."
            ),
        )
        nwbfile.add_electrode_column(
            name="icms_threshold_uA",
            description=(
                "Minimum current (microamps) at which ICMS evoked movement at the recording site. "
                "Low thresholds (<30 uA) confirm primary motor cortex (M1) recording location. "
                "NaN if not tested or no response."
            ),
        )
        # Use D99 atlas ACx coordinates when available
        # ACx convention: A_P_acx (+anterior), M_L_acx (+lateral, left hemisphere), Depth_acx (+superior/dorsal)
        ap_acx = self.session_info["A_P_acx"]
        ml_acx = self.session_info["M_L_acx"]
        depth_acx = self.session_info["Depth_acx"]
        has_acx = not (math.isnan(ap_acx) or math.isnan(ml_acx) or math.isnan(depth_acx))

        if has_acx:
            # Convert ACx convention to D99 RAS:
            # R = -M_L (left hemisphere lateral is negative R)
            # A = A_P (source A_P is +anterior, same as RAS)
            # S = Depth (both +superior/dorsal)
            d99_r_raw = -ml_acx
            d99_a_raw = ap_acx
            d99_s_raw = depth_acx

            # Look up precomputed NMT and MEBRAINS coordinates (avoids calling ANTs at runtime).
            # Returns both raw and curated sets: curated D99 is the nearest F1_(4) voxel center
            # (within 5 mm); curated NMT / MEBRAINS are the RheMAP warps of that curated D99 point.
            (
                nmt_r_raw, nmt_a_raw, nmt_s_raw,
                mebrains_r_raw, mebrains_a_raw, mebrains_s_raw,
                d99_r, d99_a, d99_s,
                nmt_r, nmt_a, nmt_s,
                mebrains_r, mebrains_a, mebrains_s,
            ) = lookup_warped_coordinates(d99_r_raw, d99_a_raw, d99_s_raw)

            # Curated M1-constrained labels (what goes in brain_region_id, displayed on the map).
            # The label curation uses the RAW coord (same policy we used in round 5); the position
            # in x/y/z is the curated coord (new in round 7).
            d99_region, d99_region_id, d99_method, d99_distance = lookup_d99_m1(ap_acx, ml_acx, depth_acx)
            charm_region, charm_region_id, charm_method, charm_distance = lookup_charm_m1(
                nmt_r_raw, nmt_a_raw, nmt_s_raw
            )
            mebrains_region, mebrains_region_id, mebrains_method, mebrains_distance = lookup_mebrains_m1(
                mebrains_r_raw, mebrains_a_raw, mebrains_s_raw
            )

            # Raw atlas voxel lookups (what goes in voxel_label_id, honest atlas answer).
            # Lookup is performed at the RAW coordinate so voxel_label_id reflects what the atlas
            # physically says at the electrode's warp output, not at the snapped M1 voxel center.
            d99_voxel_label, d99_voxel_label_id = lookup_d99_region(ap_acx, ml_acx, depth_acx)
            nmt_voxel_label, nmt_voxel_label_id = lookup_nmt_voxel(nmt_r_raw, nmt_a_raw, nmt_s_raw)
            mebrains_voxel_label, mebrains_voxel_label_id = lookup_mebrains_region(
                mebrains_r_raw, mebrains_a_raw, mebrains_s_raw
            )

            # electrode.location uses the curated D99 label so Leu sessions (whose raw D99 voxel
            # often reads S1 due to the sulcal-gap warp artifact) still display as M1, matching
            # the ICMS-verified identity.
            electrode_location = d99_region
        else:
            electrode_location = "Primary motor cortex (M1), area 4, arm area"

        # Standard NWB x/y/z: NMT v2.0-sym coordinates in PIR convention (microns).
        if has_acx:
            x_pir = -nmt_a * 1000.0  # +anterior -> +posterior, mm -> um
            y_pir = -nmt_s * 1000.0  # +superior -> +inferior, mm -> um
            z_pir = nmt_r * 1000.0   # +right stays +right, mm -> um
        else:
            x_pir = float("nan")
            y_pir = float("nan")
            z_pir = float("nan")

        # Add recording electrode with chamber grid coordinates
        nwbfile.add_electrode(
            x=x_pir,
            y=y_pir,
            z=z_pir,
            imp=float("nan"),  # Electrode impedance not recorded
            location=electrode_location,
            filtering="0.3-10kHz bandpass for spikes, 1-100Hz for LFP when available",
            group=recording_electrode_group,
            chamber_grid_ap_mm=-self.session_info["A_P"],
            chamber_grid_ml_mm=self.session_info["M_L"],
            chamber_insertion_depth_mm=self.session_info["Depth"],
            icms_effect=_normalize_icms_effect(self.session_info.get("Microstim_Effect", "")),
            icms_threshold_uA=_to_float_or_nan(self.session_info.get("Microstim_Threshold")),
        )

        # Add atlas coordinates via ndx-anatomical-localization if available.
        #
        # Schema (identical across the three tables D99, NMT, MEBRAINS):
        #   brain_region_id / brain_region               curated M1-constrained label (what the viewer reads)
        #   brain_region_lookup_method                   "exact" | "nearest_neighbor" | "no_m1_within_5mm"
        #   brain_region_distance_mm                     0.0 for exact, mm for NN, NaN for no_m1_within_5mm
        #   voxel_label_id / voxel_label                 raw atlas voxel answer (or "unlabeled" / "outside_volume")
        #
        # Invariant: method == "exact" implies brain_region_id == voxel_label_id.
        # The M1-constrained fallback is a conversion-side convenience specific to dandiset
        # 001636 (every recording site is ICMS-verified M1, <30 uA threshold); it should not
        # be interpreted as atlas authority. See table-level method strings and the
        # documentation at documentation/nearest_neighbor_region_labeling.md for details.
        if has_acx:
            method_column_description = (
                "How the curated brain_region_id was determined: "
                "'exact' = the raw atlas voxel at this coordinate is already the atlas's native "
                "primary motor cortex (M1) label, so the raw voxel answer is used; "
                "'nearest_neighbor' = the raw voxel was non-M1 or unlabeled, so the label was "
                "set to the nearest M1 voxel within 5 mm (distance in brain_region_distance_mm); "
                "'no_m1_within_5mm' = no M1 voxel within the 5 mm cap, brain_region_id is 'outside'."
            )
            distance_column_description = (
                "Euclidean distance in mm from the electrode coordinate to the nearest atlas-native M1 voxel. "
                "0.0 when brain_region_lookup_method is 'exact'; positive float for 'nearest_neighbor'; "
                "NaN for 'no_m1_within_5mm'."
            )
            voxel_label_id_column_description = (
                "Raw atlas voxel label ID at this coordinate (no interpolation). Distinct from "
                "brain_region_id, which is curated to the atlas's native M1 label; voxel_label_id "
                "is whatever the atlas says at that voxel. Special values: 'unlabeled' when the "
                "voxel is inside the template but carries label=0 (sulcal-gap artifact or simply "
                "unparcellated tissue); 'outside_volume' when the coordinate falls outside the "
                "template's bounding box."
            )
            voxel_label_column_description = (
                "Full-name form of voxel_label_id. Special values: 'unlabeled voxel (label=0)' "
                "and 'outside template volume'."
            )
            raw_coord_column_description = (
                "Raw (uncurated) atlas-space coordinate component (mm). For D99 this is the "
                "output of the author's chamber-to-D99 geometric transform (no MRI registration). "
                "For NMT and MEBRAINS this is the RheMAP warp of that raw D99 point. Distinct "
                "from the curated x / y / z columns, which hold the RheMAP warp of the nearest "
                "F1_(4) voxel center to the raw D99 coordinate (within a 5 mm cap); the curated "
                "values are what the dandi-atlas viewer renders on the map. Equal to the curated "
                "value when the raw D99 coord lies exactly on an F1 voxel center."
            )

            # D99 space and coordinates table. D99 is the author's canonical frame; coordinates
            # come directly from Dr. Turner's geometric transform (no MRI registration). M1
            # target is F1_(4) (label id 359), the D99 label for agranular frontal area F1.
            d99_space = D99v2Space()

            d99_coordinates_table = AnatomicalCoordinatesTable(
                name="D99v2AtlasCoordinates",
                target=nwbfile.electrodes,
                description=(
                    "Recording electrode coordinates in D99 macaque atlas space "
                    "(RAS orientation, mm; origin at the anterior commissure). D99 is the "
                    "author's canonical coordinate frame for this dataset. "
                    "See https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/nonhuman/macaque_tempatl/atlas_d99v2.html"
                ),
                method=(
                    "COORDINATE ORIGIN (per-electrode x/y/z). "
                    "Computed by Dr. Robert Turner (data author) from chamber-relative positions "
                    "using a geometric transform: constant AP offset (-8.2 mm, chamber center to "
                    "anterior commissure) and 35-degree coronal-plane rotation coupling ML and "
                    "Depth to the D99 R and S axes. No individual MRI registration was used; "
                    "coordinate accuracy is limited by the geometric approximation (no subject-specific warping). "
                    "REGION ANNOTATION (brain_region_id and voxel_label_id columns). "
                    "Computed by the conversion pipeline, not provided by the data author. "
                    "'voxel_label_id' is the raw D99 atlas voxel label at the coordinate (honest atlas answer). "
                    "'brain_region_id' is a curated M1-constrained label: if the raw voxel is F1_(4) "
                    "(D99 label id 359, primary motor cortex), it is preserved; otherwise the "
                    "nearest F1_(4) voxel within 5 mm is chosen, with the distance recorded in "
                    "'brain_region_distance_mm' and flagged in 'brain_region_lookup_method'. "
                    "AUTHORITY. "
                    "The curated label reflects the ICMS-verified motor identity of the recording "
                    "site (every electrode in this dataset has icms_threshold_uA < 30 uA on the "
                    "electrodes table, which is cytoarchitectonically specific to primary motor "
                    "cortex). The curation is a dataset-specific convenience for dandiset 001636 "
                    "and is not authoritative atlas output; it should not be used as a substitute "
                    "for the ICMS evidence or extended to datasets with non-motor recordings."
                ),
                space=d99_space,
            )

            d99_coordinates_table.add_column(
                name="brain_region_id",
                description=(
                    "Curated D99 M1 label (viewer-facing). Always 'F1_(4)' unless the electrode "
                    "coordinate is > 5 mm from any D99 F1 voxel, in which case 'outside'."
                ),
            )
            d99_coordinates_table.add_column(
                name="brain_region_lookup_method",
                description=method_column_description,
            )
            d99_coordinates_table.add_column(
                name="brain_region_distance_mm",
                description=distance_column_description,
            )
            d99_coordinates_table.add_column(
                name="voxel_label_id",
                description=voxel_label_id_column_description,
            )
            d99_coordinates_table.add_column(
                name="voxel_label",
                description=voxel_label_column_description,
            )
            d99_coordinates_table.add_column(name="x_raw", description=raw_coord_column_description)
            d99_coordinates_table.add_column(name="y_raw", description=raw_coord_column_description)
            d99_coordinates_table.add_column(name="z_raw", description=raw_coord_column_description)

            d99_coordinates_table.add_row(
                x=d99_r,
                y=d99_a,
                z=d99_s,
                localized_entity=0,  # Index into electrode table (single recording electrode).
                brain_region=d99_region,
                brain_region_id=d99_region_id,
                brain_region_lookup_method=d99_method,
                brain_region_distance_mm=d99_distance,
                voxel_label=d99_voxel_label,
                voxel_label_id=d99_voxel_label_id,
                x_raw=d99_r_raw,
                y_raw=d99_a_raw,
                z_raw=d99_s_raw,
            )

            localization = Localization()
            spaces_to_add = [d99_space]
            tables_to_add = [d99_coordinates_table]

            # NMT v2.0-sym space and coordinates table (coordinates derived via RheMAP warp of D99).
            # M1 target is CHARM level-4 M1 (index 79); CHARM never subdivides M1 at any level.
            nmt_space = NMTv2Space()

            nmt_coordinates_table = AnatomicalCoordinatesTable(
                name="NMTv2AtlasCoordinates",
                target=nwbfile.electrodes,
                description=(
                    "Recording electrode coordinates in NMT v2.0-sym (NIMH Macaque Template, "
                    "symmetric) atlas space (RAS orientation, mm; origin at ear bar zero). "
                    "Coordinates are derived by nonlinear warping of the author's D99 coordinate "
                    "into NMT space. "
                    "See https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/nonhuman/macaque_tempatl/template_nmtv2.html"
                ),
                method=(
                    "COORDINATE ORIGIN (per-electrode x/y/z). "
                    "The author-provided D99 coordinate (geometric transform by Dr. Robert Turner, "
                    "no MRI registration) is warped into NMT v2.0-sym space using the RheMAP "
                    "pre-computed nonlinear composite warp (NMTv2.0-sym_to_D99_CompositeWarp.nii.gz, "
                    "applied in reverse for point transforms; RAS<->LPS conversion around the ANTs "
                    "call; Sirmpilatze & Klink 2020, DOI:10.5281/zenodo.4748589). The NMT coordinate "
                    "inherits the uncertainty of the source D99 geometric transform and adds the "
                    "RheMAP warp uncertainty on top. "
                    "REGION ANNOTATION (brain_region_id and voxel_label_id columns). "
                    "Computed by the conversion pipeline, not provided by the data author. "
                    "'voxel_label_id' is the raw CHARM level-4 voxel label at the coordinate "
                    "(honest atlas answer). 'brain_region_id' is a curated M1-constrained label: "
                    "if the raw voxel is M1 (CHARM level-4 index 79, primary motor cortex), it is "
                    "preserved; otherwise the nearest M1 voxel within 5 mm is chosen, with the "
                    "distance in 'brain_region_distance_mm' and the flag in 'brain_region_lookup_method'. "
                    "The CHARM level-4 parcellation does not subdivide M1 (M1 remains a single "
                    "label at every CHARM level 4-6), so 'brain_region_id' always reads 'M1' on "
                    "this dataset. Many electrodes land in the central sulcus fundus, where "
                    "post-mortem tissue shrinkage opens unlabeled gaps in the template that do "
                    "not exist in vivo; the curation absorbs this artifact. "
                    "AUTHORITY. "
                    "The curated label reflects the ICMS-verified motor identity of the recording "
                    "site (see 'icms_threshold_uA' on the electrodes table). Unconstrained "
                    "nearest-neighbor (snapping to any labeled region) was tested and rejected: "
                    "it mislabeled 100% of Leu electrodes as somatosensory cortex, because the "
                    "S1 bank of the sulcal gap is geometrically closer in the template but "
                    "functionally wrong for these ICMS-confirmed M1 recordings. The M1-constrained "
                    "curation is a dataset-specific convenience for dandiset 001636."
                ),
                space=nmt_space,
            )

            nmt_coordinates_table.add_column(
                name="brain_region_id",
                description=(
                    "Curated CHARM M1 label (viewer-facing). Always 'M1' unless the electrode "
                    "coordinate is > 5 mm from any CHARM M1 voxel, in which case 'outside'."
                ),
            )
            nmt_coordinates_table.add_column(
                name="brain_region_lookup_method",
                description=method_column_description,
            )
            nmt_coordinates_table.add_column(
                name="brain_region_distance_mm",
                description=distance_column_description,
            )
            nmt_coordinates_table.add_column(
                name="voxel_label_id",
                description=voxel_label_id_column_description,
            )
            nmt_coordinates_table.add_column(
                name="voxel_label",
                description=voxel_label_column_description,
            )
            nmt_coordinates_table.add_column(name="x_raw", description=raw_coord_column_description)
            nmt_coordinates_table.add_column(name="y_raw", description=raw_coord_column_description)
            nmt_coordinates_table.add_column(name="z_raw", description=raw_coord_column_description)

            nmt_coordinates_table.add_row(
                x=nmt_r,
                y=nmt_a,
                z=nmt_s,
                localized_entity=0,
                brain_region=charm_region,
                brain_region_id=charm_region_id,
                brain_region_lookup_method=charm_method,
                brain_region_distance_mm=charm_distance,
                voxel_label=nmt_voxel_label,
                voxel_label_id=nmt_voxel_label_id,
                x_raw=nmt_r_raw,
                y_raw=nmt_a_raw,
                z_raw=nmt_s_raw,
            )

            spaces_to_add.append(nmt_space)
            tables_to_add.append(nmt_coordinates_table)

            # MEBRAINS space and coordinates table (coordinates derived via RheMAP warp of D99).
            # M1 target is 4a (label 301) + 4p (label 303) left; MEBRAINS is the only atlas of
            # the three whose native parcellation subdivides M1 (anterior vs posterior).
            mebrains_space = MEBRAINSSpace()

            mebrains_coordinates_table = AnatomicalCoordinatesTable(
                name="MEBRAINSAtlasCoordinates",
                target=nwbfile.electrodes,
                description=(
                    "Recording electrode coordinates in MEBRAINS 1.0 (population-based macaque "
                    "template; Balan et al. 2024) atlas space (RAS orientation, mm; origin at "
                    "the anterior commissure). Coordinates are derived by nonlinear warping of "
                    "the author's D99 coordinate into MEBRAINS space. "
                    "See https://doi.org/10.1162/imag_a_00077"
                ),
                method=(
                    "COORDINATE ORIGIN (per-electrode x/y/z). "
                    "The author-provided D99 coordinate (geometric transform by Dr. Robert Turner, "
                    "no MRI registration) is warped into MEBRAINS space using the RheMAP "
                    "pre-computed nonlinear composite warp (MEBRAINS_to_D99_CompositeWarp.nii.gz, "
                    "applied in reverse for point transforms; RAS<->LPS conversion around the "
                    "ANTs call; https://gin.g-node.org/ChrisKlink/RheMAP). The MEBRAINS coordinate "
                    "inherits the uncertainty of the source D99 geometric transform and adds the "
                    "RheMAP warp uncertainty on top. "
                    "REGION ANNOTATION (brain_region_id and voxel_label_id columns). "
                    "Computed by the conversion pipeline, not provided by the data author. "
                    "'voxel_label_id' is the raw MEBRAINS voxel label at the coordinate (honest "
                    "atlas answer, numeric string form of the Julich Brain Macaque label ID). "
                    "'brain_region_id' is a curated M1-constrained label: if the raw voxel is 4a "
                    "(301) or 4p (303), it is preserved (both are M1 subdivisions, anterior vs "
                    "posterior); otherwise the nearest M1 voxel (4a or 4p) within 5 mm is chosen, "
                    "with the distance in 'brain_region_distance_mm' and the flag in "
                    "'brain_region_lookup_method'. MEBRAINS has wider sulcal gaps than D99 due to "
                    "post-mortem tissue processing, causing many electrodes to land in unlabeled "
                    "voxels at the central sulcus fundus; the curation absorbs this. "
                    "AUTHORITY. "
                    "The curated label reflects the ICMS-verified motor identity of the recording "
                    "site (see 'icms_threshold_uA' on the electrodes table). MEBRAINS is the only "
                    "atlas of the three whose native parcellation subdivides M1, so the 4a/4p "
                    "distinction is the finest-granularity M1 anatomical position this dataset "
                    "carries. The M1-constrained curation is a dataset-specific convenience for "
                    "dandiset 001636."
                ),
                space=mebrains_space,
            )

            mebrains_coordinates_table.add_column(
                name="brain_region_id",
                description=(
                    "Curated MEBRAINS M1 label (viewer-facing, numeric string form). '301' for 4a "
                    "left (anterior M1), '303' for 4p left (posterior M1). 'outside' only if the "
                    "electrode coordinate is > 5 mm from any MEBRAINS M1 voxel."
                ),
            )
            mebrains_coordinates_table.add_column(
                name="brain_region_lookup_method",
                description=method_column_description,
            )
            mebrains_coordinates_table.add_column(
                name="brain_region_distance_mm",
                description=distance_column_description,
            )
            mebrains_coordinates_table.add_column(
                name="voxel_label_id",
                description=voxel_label_id_column_description,
            )
            mebrains_coordinates_table.add_column(
                name="voxel_label",
                description=voxel_label_column_description,
            )
            mebrains_coordinates_table.add_column(name="x_raw", description=raw_coord_column_description)
            mebrains_coordinates_table.add_column(name="y_raw", description=raw_coord_column_description)
            mebrains_coordinates_table.add_column(name="z_raw", description=raw_coord_column_description)

            mebrains_coordinates_table.add_row(
                x=mebrains_r,
                y=mebrains_a,
                z=mebrains_s,
                localized_entity=0,
                brain_region=mebrains_region,
                brain_region_id=mebrains_region_id,
                brain_region_lookup_method=mebrains_method,
                brain_region_distance_mm=mebrains_distance,
                voxel_label=mebrains_voxel_label,
                voxel_label_id=mebrains_voxel_label_id,
                x_raw=mebrains_r_raw,
                y_raw=mebrains_a_raw,
                z_raw=mebrains_s_raw,
            )

            spaces_to_add.append(mebrains_space)
            tables_to_add.append(mebrains_coordinates_table)

            localization.add_spaces(spaces_to_add)
            # Add localization to the NWBFile before adding the coordinates tables,
            # so that both the DynamicTableRegion (localized_entity) and its target
            # (nwbfile.electrodes) share a common ancestor during validation.
            nwbfile.add_lab_meta_data(localization)
            localization.add_anatomical_coordinates_tables(tables_to_add)

        if self.verbose:
            print(f"Added electrode configuration: 1 recording electrode in electrodes table")
            if has_acx:
                print(f"Added D99 atlas coordinates (RAS mm): R={d99_r:.2f}, A={d99_a:.2f}, S={d99_s:.2f}")
                print(
                    f"D99 curated: {d99_region_id} ({d99_method}, {d99_distance:.2f} mm); "
                    f"raw voxel: {d99_voxel_label_id}"
                )
                print(f"Added NMT v2.0-sym coordinates (RAS mm): R={nmt_r:.2f}, A={nmt_a:.2f}, S={nmt_s:.2f}")
                print(
                    f"NMT curated: {charm_region_id} ({charm_method}, {charm_distance:.2f} mm); "
                    f"raw voxel: {nmt_voxel_label_id}"
                )
                print(f"Added MEBRAINS coordinates (RAS mm): R={mebrains_r:.2f}, A={mebrains_a:.2f}, S={mebrains_s:.2f}")
                print(
                    f"MEBRAINS curated: {mebrains_region_id} ({mebrains_method}, {mebrains_distance:.2f} mm); "
                    f"raw voxel: {mebrains_voxel_label_id}"
                )