import logging
import math
from functools import lru_cache
from pathlib import Path
from typing import Optional

import nibabel as nib
import numpy as np
from scipy.spatial import cKDTree
import pandas as pd
from ndx_anatomical_localization import AnatomicalCoordinatesTable, Localization, Space
from pydantic import FilePath
from pynwb import NWBFile

from neuroconv.basedatainterface import BaseDataInterface

logger = logging.getLogger(__name__)


def _to_float_or_nan(value) -> float:
    """Convert a value to float, returning NaN for non-numeric values like 'nt' or NaN."""
    try:
        result = float(value)
        return result
    except (ValueError, TypeError):
        return float("nan")


def _normalize_icms_effect(raw: str) -> str:
    """Normalize ICMS effect descriptions to consistent, expanded form.

    Expands abbreviations (ext. -> extension, flex. -> flexion, etc.),
    standardizes case, and maps special values (nt -> not_tested, nr -> no_response).
    """
    if pd.isna(raw) or raw == "":
        return ""
    raw = str(raw).strip()
    if raw.lower() in ("nt", "not tested"):
        return "not_tested"
    if raw.lower() in ("nr", "no response"):
        return "no_response"

    # Expand common abbreviations (order matters: longer patterns first)
    result = raw.lower()
    result = result.replace("ext. rotation", "external rotation")
    result = result.replace("rad. dev.", "radial deviation")
    result = result.replace("ulnar dev.", "ulnar deviation")
    result = result.replace("ext.", "extension")
    result = result.replace("flex.", "flexion")
    result = result.replace("abd.", "abduction")
    result = result.replace("sup.", "supination")
    # Handle forms without trailing periods (word boundaries via space or end-of-string)
    import re
    result = re.sub(r"\bext\b", "extension", result)
    result = re.sub(r"\bflex\b", "flexion", result)
    result = re.sub(r"\badduct\b", "adduction", result)
    return result

_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent.parent

# D99 atlas data directory (relative to project root).
# Required files (download from https://afni.nimh.nih.gov/pub/dist/atlases/macaque/d99/D99_v2.0_dist.tgz):
#   - D99_atlas_v2.0.nii.gz  (813K, parcellation volume)
#   - D99_v2.0_labels_semicolon.txt  (20K, label names)
# Extract to: <project_root>/data/d99_atlas/D99_v2.0_dist/
_D99_ATLAS_DIR = _PROJECT_ROOT / "data" / "d99_atlas" / "D99_v2.0_dist"

# RheMAP warp file for D99 -> NMT v2.0-sym coordinate conversion.
# Download from https://zenodo.org/records/4748589 (warps_final_NMTv2.0-sym.zip).
# For point transforms, the warp direction is REVERSED: use the NMTv2.0-sym_to_D99 warp
# to move a point FROM D99 TO NMT v2.0-sym (ANTs convention).
_RHEMAP_WARP_PATH = _PROJECT_ROOT / "data" / "rhemap_warps" / "NMTv2.0-sym_to_D99_CompositeWarp.nii.gz"

# RheMAP warp file for D99 -> MEBRAINS coordinate conversion.
# Download from https://gin.g-node.org/ChrisKlink/RheMAP (warps/final/).
# Same reversed-direction ANTs convention as the NMT warp above.
_MEBRAINS_WARP_PATH = _PROJECT_ROOT / "data" / "rhemap_warps" / "MEBRAINS_to_D99_CompositeWarp.nii.gz"

# MEBRAINS atlas data directory (relative to project root).
# Required files:
#   - MEBRAINS_parcellation.nii.gz  (parcellation volume)
#   - MEBRAINS_labels.json  (label ID -> region name mapping)
_MEBRAINS_ATLAS_DIR = _PROJECT_ROOT / "data" / "mebrains"

# Precomputed warp results (CSV). Generated by scripts/precompute_warped_coordinates.py.
# Contains D99 -> NMT and D99 -> MEBRAINS coordinates for all unique electrode positions.
# This avoids calling ANTs at conversion time (~3s per warp, ~30 min for 358 sessions).
_WARPED_COORDS_PATH = (
    _PROJECT_ROOT / "src" / "turner_lab_to_nwb" / "asap_m1_mptp"
    / "assets" / "metadata_table" / "warped_coordinates.csv"
)

# CHARM level 4 atlas on NMT v2.0-sym (for M1 region lookup in NMT space).
# CHARM is the native hierarchical parcellation for NMT. Level 4 is the first level
# where M1 (primary_motor_cortex, index 79) is separated from premotor and SMA.
_CHARM_ATLAS_PATH = (
    _PROJECT_ROOT / "data" / "nmt_v2" / "NMT_v2.0_sym" / "NMT_v2.0_sym"
    / "supplemental_CHARM" / "CHARM_4_in_NMT_v2.0_sym.nii.gz"
)
_CHARM_KEY_PATH = (
    _PROJECT_ROOT / "data" / "nmt_v2" / "NMT_v2.0_sym"
    / "tables_CHARM" / "CHARM_key_4.txt"
)

# M1-constrained nearest-neighbor parameters.
_MAX_NEAREST_MM = 5.0
_CHARM_M1_INDEX = 79
_MEBRAINS_M1_LABELS = {301: "4a left", 303: "4p left"}


@lru_cache(maxsize=1)
def _load_d99_atlas() -> tuple[np.ndarray, np.ndarray, dict]:
    """Load D99 atlas data (cached across sessions).

    Returns
    -------
    atlas_data : np.ndarray
        3D array of label IDs
    inv_affine : np.ndarray
        Inverse affine matrix (world RAS mm -> voxel indices)
    labels : dict
        Mapping from label_id to {"abbreviation": str, "full_name": str}
    """
    atlas_path = _D99_ATLAS_DIR / "D99_atlas_v2.0.nii.gz"
    labels_path = _D99_ATLAS_DIR / "D99_v2.0_labels_semicolon.txt"

    atlas = nib.load(str(atlas_path))
    atlas_data = np.asarray(atlas.dataobj)
    inv_affine = np.linalg.inv(atlas.affine)

    # Parse label file: id;abbreviation;full_name[;category;subcategory]
    labels = {}
    with open(labels_path) as f:
        for line in f:
            parts = line.strip().split(";")
            if len(parts) >= 3:
                label_id = int(parts[0])
                abbreviation = parts[1].strip()
                full_name = parts[2].strip().strip('"')
                labels[label_id] = {"abbreviation": abbreviation, "full_name": full_name}

    return atlas_data, inv_affine, labels


@lru_cache(maxsize=1)
def _load_mebrains_atlas() -> tuple[np.ndarray, np.ndarray, dict]:
    """Load MEBRAINS atlas data (cached across sessions).

    Returns
    -------
    atlas_data : np.ndarray
        3D array of label IDs
    inv_affine : np.ndarray
        Inverse affine matrix (world RAS mm -> voxel indices)
    labels : dict
        Mapping from label_id to {"name": str}
    """
    import json

    atlas_path = _MEBRAINS_ATLAS_DIR / "MEBRAINS_parcellation.nii.gz"
    labels_path = _MEBRAINS_ATLAS_DIR / "MEBRAINS_labels.json"

    atlas = nib.load(str(atlas_path))
    atlas_data = np.asarray(atlas.dataobj)
    inv_affine = np.linalg.inv(atlas.affine)

    with open(labels_path) as f:
        raw_labels = json.load(f)
    labels = {int(k): {"name": v} for k, v in raw_labels.items()}

    return atlas_data, inv_affine, labels


@lru_cache(maxsize=1)
def _load_charm_m1_tree():
    """Load CHARM level 4 atlas and build KD-tree of M1 voxels in world RAS mm (cached).

    Returns
    -------
    m1_tree : cKDTree
        KD-tree of M1 voxel positions in NMT RAS world coordinates (mm).
    atlas_data : np.ndarray
        3D array of CHARM label IDs.
    inv_affine : np.ndarray
        Inverse affine (world RAS mm -> voxel indices).
    """
    atlas = nib.load(str(_CHARM_ATLAS_PATH))
    atlas_data = np.asarray(atlas.dataobj)
    affine = atlas.affine
    inv_affine = np.linalg.inv(affine)

    m1_voxels = np.argwhere(atlas_data == _CHARM_M1_INDEX)
    m1_world_coords = nib.affines.apply_affine(affine, m1_voxels)
    m1_tree = cKDTree(m1_world_coords)

    return m1_tree, atlas_data, inv_affine


@lru_cache(maxsize=1)
def _load_mebrains_m1_tree():
    """Build KD-tree of MEBRAINS M1 voxels (4a + 4p) in world RAS mm (cached).

    Reuses atlas data from _load_mebrains_atlas().

    Returns
    -------
    m1_tree : cKDTree
        KD-tree of M1 voxel positions in MEBRAINS RAS world coordinates (mm).
    m1_voxels : np.ndarray
        (N, 3) array of M1 voxel indices (for label lookup after query).
    """
    atlas_data, inv_affine, _ = _load_mebrains_atlas()
    affine = np.linalg.inv(inv_affine)

    m1_mask = np.isin(atlas_data, list(_MEBRAINS_M1_LABELS.keys()))
    m1_voxels = np.argwhere(m1_mask)
    m1_world_coords = nib.affines.apply_affine(affine, m1_voxels)
    m1_tree = cKDTree(m1_world_coords)

    return m1_tree, m1_voxels


def lookup_charm_m1(nmt_r: float, nmt_a: float, nmt_s: float) -> tuple[str, str, str, float]:
    """Look up CHARM M1 region for an NMT RAS coordinate, with M1-constrained nearest-neighbor.

    Parameters
    ----------
    nmt_r, nmt_a, nmt_s : float
        NMT v2.0-sym RAS coordinates (mm).

    Returns
    -------
    region_name : str
        "primary_motor_cortex" if within distance cap, else "outside atlas".
    region_id : str
        "M1" if within distance cap, else "outside".
    method : str
        "exact", "nearest_neighbor", or "outside".
    distance_mm : float
        0.0 for exact, Euclidean distance for nearest_neighbor, NaN for outside.
    """
    m1_tree, atlas_data, inv_affine = _load_charm_m1_tree()

    world_coord = np.array([nmt_r, nmt_a, nmt_s])
    voxel = np.round(nib.affines.apply_affine(inv_affine, world_coord)).astype(int)

    if not all(0 <= voxel[i] < atlas_data.shape[i] for i in range(3)):
        return "outside atlas", "outside", "outside", float("nan")

    label_id = int(atlas_data[tuple(voxel)])
    if label_id == _CHARM_M1_INDEX:
        return "primary_motor_cortex", "M1", "exact", 0.0

    dist_mm, _ = m1_tree.query(world_coord)
    if dist_mm <= _MAX_NEAREST_MM:
        return "primary_motor_cortex", "M1", "nearest_neighbor", round(float(dist_mm), 4)

    return "outside atlas", "outside", "outside", float("nan")


def lookup_mebrains_m1(mebrains_r: float, mebrains_a: float, mebrains_s: float) -> tuple[str, str, str, float]:
    """Look up MEBRAINS M1 subdivision for a MEBRAINS RAS coordinate, with M1-constrained nearest-neighbor.

    Parameters
    ----------
    mebrains_r, mebrains_a, mebrains_s : float
        MEBRAINS RAS coordinates (mm).

    Returns
    -------
    region_name : str
        "4a left" or "4p left" if within distance cap, else "outside atlas".
    region_id : str
        "301" or "303" if within distance cap, else "outside".
    method : str
        "exact", "nearest_neighbor", or "outside".
    distance_mm : float
        0.0 for exact, Euclidean distance for nearest_neighbor, NaN for outside.
    """
    atlas_data, inv_affine, _ = _load_mebrains_atlas()
    m1_tree, m1_voxels = _load_mebrains_m1_tree()

    world_coord = np.array([mebrains_r, mebrains_a, mebrains_s])
    voxel = np.round(nib.affines.apply_affine(inv_affine, world_coord)).astype(int)

    if not all(0 <= voxel[i] < atlas_data.shape[i] for i in range(3)):
        return "outside atlas", "outside", "outside", float("nan")

    label_id = int(atlas_data[tuple(voxel)])
    if label_id in _MEBRAINS_M1_LABELS:
        return _MEBRAINS_M1_LABELS[label_id], str(label_id), "exact", 0.0

    dist_mm, idx = m1_tree.query(world_coord)
    if dist_mm <= _MAX_NEAREST_MM:
        nearest_voxel = tuple(m1_voxels[idx])
        nearest_id = int(atlas_data[nearest_voxel])
        return _MEBRAINS_M1_LABELS[nearest_id], str(nearest_id), "nearest_neighbor", round(float(dist_mm), 4)

    return "outside atlas", "outside", "outside", float("nan")


def lookup_mebrains_region(mebrains_r: float, mebrains_a: float, mebrains_s: float) -> tuple[str, str]:
    """Look up the MEBRAINS atlas region for a given MEBRAINS RAS coordinate.

    Parameters
    ----------
    mebrains_r : float
        Right coordinate in MEBRAINS RAS (mm)
    mebrains_a : float
        Anterior coordinate in MEBRAINS RAS (mm)
    mebrains_s : float
        Superior coordinate in MEBRAINS RAS (mm)

    Returns
    -------
    region_name : str
        Region name from MEBRAINS labels (e.g., "4p left")
    region_id : str
        String label ID from MEBRAINS (e.g., "303")
    """
    atlas_data, inv_affine, labels = _load_mebrains_atlas()

    world_coord = np.array([mebrains_r, mebrains_a, mebrains_s])
    voxel = nib.affines.apply_affine(inv_affine, world_coord)
    voxel_idx = tuple(np.round(voxel).astype(int))

    if all(0 <= voxel_idx[i] < atlas_data.shape[i] for i in range(3)):
        label_id = int(atlas_data[voxel_idx])
        if label_id > 0 and label_id in labels:
            return labels[label_id]["name"], str(label_id)

    return "outside atlas", "outside"


@lru_cache(maxsize=1)
def _load_warped_coordinates():
    """Load precomputed warped coordinates CSV (cached across sessions).

    Returns a dict mapping (d99_r, d99_a, d99_s) rounded keys to
    (nmt_r, nmt_a, nmt_s, mebrains_r, mebrains_a, mebrains_s) tuples.
    """
    import pandas as pd

    if not _WARPED_COORDS_PATH.exists():
        raise FileNotFoundError(
            f"Precomputed warp file not found at {_WARPED_COORDS_PATH}. "
            "Run: uv run python src/turner_lab_to_nwb/asap_m1_mptp/scripts/precompute_warped_coordinates.py"
        )

    df = pd.read_csv(_WARPED_COORDS_PATH)
    lookup = {}
    for _, row in df.iterrows():
        key = (round(row["d99_r"], 6), round(row["d99_a"], 6), round(row["d99_s"], 6))
        lookup[key] = (
            row["nmt_r"], row["nmt_a"], row["nmt_s"],
            row["mebrains_r"], row["mebrains_a"], row["mebrains_s"],
        )
    return lookup


def lookup_warped_coordinates(
    d99_r: float, d99_a: float, d99_s: float
) -> tuple[float, float, float, float, float, float]:
    """Look up precomputed NMT and MEBRAINS coordinates for a D99 RAS position.

    Parameters
    ----------
    d99_r, d99_a, d99_s : float
        D99 RAS coordinates (mm)

    Returns
    -------
    tuple of (nmt_r, nmt_a, nmt_s, mebrains_r, mebrains_a, mebrains_s)

    Raises
    ------
    KeyError
        If the coordinate is not in the precomputed table. Regenerate with:
        uv run python src/turner_lab_to_nwb/asap_m1_mptp/scripts/precompute_warped_coordinates.py
    """
    lookup = _load_warped_coordinates()
    key = (round(d99_r, 6), round(d99_a, 6), round(d99_s, 6))
    if key not in lookup:
        raise KeyError(
            f"D99 coordinate ({d99_r}, {d99_a}, {d99_s}) not found in precomputed warp table. "
            "Regenerate with: uv run python src/turner_lab_to_nwb/asap_m1_mptp/scripts/precompute_warped_coordinates.py"
        )
    return lookup[key]


def lookup_d99_region(ap_acx: float, ml_acx: float, depth_acx: float) -> tuple[str, str]:
    """Look up the D99 atlas region for a given ACx coordinate.

    Parameters
    ----------
    ap_acx : float
        Anterior-posterior coordinate (+anterior, mm)
    ml_acx : float
        Medial-lateral coordinate (+lateral left, mm)
    depth_acx : float
        Depth coordinate (+superior/dorsal, mm)

    Returns
    -------
    full_name : str
        Full region name from D99 labels
    abbreviation : str
        Region abbreviation from D99 labels
    """
    atlas_data, inv_affine, labels = _load_d99_atlas()

    # Convert ACx to D99 RAS world coordinates (AC is at origin 0,0,0)
    r = -ml_acx  # left hemisphere = negative R
    a = ap_acx
    s = depth_acx

    world_coord = np.array([r, a, s])
    voxel = nib.affines.apply_affine(inv_affine, world_coord)
    voxel_idx = tuple(np.round(voxel).astype(int))

    # Check bounds
    if all(0 <= voxel_idx[i] < atlas_data.shape[i] for i in range(3)):
        label_id = int(atlas_data[voxel_idx])
        if label_id > 0 and label_id in labels:
            return labels[label_id]["full_name"], labels[label_id]["abbreviation"]

    return "outside atlas", "outside"


def convert_d99_to_nmt(r_d99: float, a_d99: float, s_d99: float) -> tuple[float, float, float]:
    """Convert a D99 RAS coordinate (mm) to NMT v2.0-sym RAS (mm) using a RheMAP warp.

    Uses the pre-computed nonlinear warp from RheMAP (Sirmpilatze & Klink, 2020).
    ANTs operates in LPS+ internally, so RAS coordinates are converted to LPS before
    applying the warp and converted back afterward. For point transforms, the warp
    direction is reversed: the NMTv2.0-sym_to_D99 warp moves points FROM D99 TO NMT.

    Parameters
    ----------
    r_d99 : float
        Right coordinate in D99 RAS (mm)
    a_d99 : float
        Anterior coordinate in D99 RAS (mm)
    s_d99 : float
        Superior coordinate in D99 RAS (mm)

    Returns
    -------
    tuple of (r_nmt, a_nmt, s_nmt) in NMT v2.0-sym RAS (mm).

    Raises
    ------
    FileNotFoundError
        If the RheMAP warp file is not found.
    """
    if not _RHEMAP_WARP_PATH.exists():
        raise FileNotFoundError(
            f"RheMAP warp file not found at {_RHEMAP_WARP_PATH}. "
            "Download warps_final_NMTv2.0-sym.zip from https://zenodo.org/records/4748589 "
            "and extract NMTv2.0-sym_to_D99_CompositeWarp.nii.gz to data/rhemap_warps/"
        )

    import ants
    import pandas as pd

    # RAS to LPS (negate R and A)
    l_d99 = -r_d99
    p_d99 = -a_d99
    s_lps = s_d99

    points = pd.DataFrame({"x": [l_d99], "y": [p_d99], "z": [s_lps]})

    transformed = ants.apply_transforms_to_points(
        dim=3,
        points=points,
        transformlist=[str(_RHEMAP_WARP_PATH)],
    )

    # LPS back to RAS (negate L and P)
    r_nmt = -transformed["x"].values[0]
    a_nmt = -transformed["y"].values[0]
    s_nmt = transformed["z"].values[0]

    return (float(r_nmt), float(a_nmt), float(s_nmt))


def batch_convert_d99_to_nmt(
    r_d99: np.ndarray, a_d99: np.ndarray, s_d99: np.ndarray
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Convert multiple D99 RAS coordinates to NMT v2.0-sym RAS in a single warp call.

    Same as convert_d99_to_nmt but processes all coordinates at once, which is
    much faster (~3s total vs ~3s per coordinate) since the warp field is loaded once.

    Parameters
    ----------
    r_d99, a_d99, s_d99 : np.ndarray
        Arrays of D99 RAS coordinates (mm)

    Returns
    -------
    tuple of (r_nmt, a_nmt, s_nmt) arrays in NMT v2.0-sym RAS (mm).

    Raises
    ------
    FileNotFoundError
        If the RheMAP warp file is not found.
    """
    if not _RHEMAP_WARP_PATH.exists():
        raise FileNotFoundError(
            f"RheMAP warp file not found at {_RHEMAP_WARP_PATH}. "
            "Download warps_final_NMTv2.0-sym.zip from https://zenodo.org/records/4748589 "
            "and extract NMTv2.0-sym_to_D99_CompositeWarp.nii.gz to data/rhemap_warps/"
        )

    import ants
    import pandas as pd

    points = pd.DataFrame({"x": -np.asarray(r_d99), "y": -np.asarray(a_d99), "z": np.asarray(s_d99)})
    transformed = ants.apply_transforms_to_points(dim=3, points=points, transformlist=[str(_RHEMAP_WARP_PATH)])
    return (-transformed["x"].values, -transformed["y"].values, transformed["z"].values)


def convert_d99_to_mebrains(r_d99: float, a_d99: float, s_d99: float) -> tuple[float, float, float]:
    """Convert a D99 RAS coordinate (mm) to MEBRAINS RAS (mm) using a RheMAP warp.

    Uses the pre-computed nonlinear warp from RheMAP (G-NODE repository).
    Same RAS/LPS and reversed-direction conventions as convert_d99_to_nmt.

    Parameters
    ----------
    r_d99 : float
        Right coordinate in D99 RAS (mm)
    a_d99 : float
        Anterior coordinate in D99 RAS (mm)
    s_d99 : float
        Superior coordinate in D99 RAS (mm)

    Returns
    -------
    tuple of (r, a, s) in MEBRAINS RAS (mm).

    Raises
    ------
    FileNotFoundError
        If the RheMAP warp file is not found.
    """
    if not _MEBRAINS_WARP_PATH.exists():
        raise FileNotFoundError(
            f"RheMAP warp file not found at {_MEBRAINS_WARP_PATH}. "
            "Download from https://gin.g-node.org/ChrisKlink/RheMAP (warps/final/) "
            "and place MEBRAINS_to_D99_CompositeWarp.nii.gz in data/rhemap_warps/"
        )

    import ants
    import pandas as pd

    # RAS to LPS (negate R and A)
    points = pd.DataFrame({"x": [-r_d99], "y": [-a_d99], "z": [s_d99]})

    transformed = ants.apply_transforms_to_points(
        dim=3,
        points=points,
        transformlist=[str(_MEBRAINS_WARP_PATH)],
    )

    # LPS back to RAS (negate L and P)
    r_mebrains = -transformed["x"].values[0]
    a_mebrains = -transformed["y"].values[0]
    s_mebrains = transformed["z"].values[0]

    return (float(r_mebrains), float(a_mebrains), float(s_mebrains))


def batch_convert_d99_to_mebrains(
    r_d99: np.ndarray, a_d99: np.ndarray, s_d99: np.ndarray
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Convert multiple D99 RAS coordinates to MEBRAINS RAS in a single warp call.

    Same as convert_d99_to_mebrains but processes all coordinates at once.

    Parameters
    ----------
    r_d99, a_d99, s_d99 : np.ndarray
        Arrays of D99 RAS coordinates (mm)

    Returns
    -------
    tuple of (r, a, s) arrays in MEBRAINS RAS (mm).

    Raises
    ------
    FileNotFoundError
        If the RheMAP warp file is not found.
    """
    if not _MEBRAINS_WARP_PATH.exists():
        raise FileNotFoundError(
            f"RheMAP warp file not found at {_MEBRAINS_WARP_PATH}. "
            "Download from https://gin.g-node.org/ChrisKlink/RheMAP (warps/final/) "
            "and place MEBRAINS_to_D99_CompositeWarp.nii.gz in data/rhemap_warps/"
        )

    import ants
    import pandas as pd

    points = pd.DataFrame({"x": -np.asarray(r_d99), "y": -np.asarray(a_d99), "z": np.asarray(s_d99)})
    transformed = ants.apply_transforms_to_points(dim=3, points=points, transformlist=[str(_MEBRAINS_WARP_PATH)])
    return (-transformed["x"].values, -transformed["y"].values, transformed["z"].values)


class M1MPTPElectrodesInterface(BaseDataInterface):
    """Data interface for Turner Lab M1 MPTP electrode setup (recording and stimulation electrodes)."""

    keywords = ("electrodes", "recording electrodes", "stimulation electrodes", "antidromic identification")
    associated_suffixes = (".mat",)
    info = "Interface for Turner Lab M1 MPTP electrode configuration including recording and stimulation electrodes"

    def __init__(
        self,
        file_path: FilePath,
        session_metadata: dict,
        verbose: bool = False,
    ):
        """
        Initialize the M1MPTPElectrodesInterface.

        Parameters
        ----------
        file_path : FilePath
            Path to the first Turner Lab .mat file (used for session metadata extraction)
        session_metadata : dict
            Metadata for all units in this session (each unit contains session-level info)
        verbose : bool, optional
            Whether to print verbose output, by default False
        """
        super().__init__(verbose=verbose)
        self.base_file_path = Path(file_path)
        self.session_metadata = session_metadata
        
        # Extract session-level info from first unit (all units have same session info)
        if self.session_metadata:
            first_unit = self.session_metadata[0]
            self.session_info = {
                "Animal": first_unit["Animal"],
                "MPTP": first_unit["MPTP"],
                "DateCollected": first_unit["DateCollected"],
                "A_P": first_unit["A_P"],
                "M_L": first_unit["M_L"],
                "Depth": first_unit["Depth"],
                "A_P_acx": first_unit.get("A_P_acx", float("nan")),
                "M_L_acx": first_unit.get("M_L_acx", float("nan")),
                "Depth_acx": first_unit.get("Depth_acx", float("nan")),
                "Microstim_Effect": first_unit.get("Microstim_Effect", first_unit.get("Microtim_Effect", "")),
                "Microstim_Threshold": first_unit.get("Microstim_Threshold", float("nan")),
            }

    def add_to_nwbfile(self, nwbfile: NWBFile, metadata: Optional[dict] = None) -> None:
        """
        Add electrode configuration to the NWB file.

        Parameters
        ----------
        nwbfile : NWBFile
            The NWB file object to add electrode configuration to
        metadata : dict, optional
            Metadata dictionary
        """
        if metadata is None:
            metadata = self.get_metadata()

        # Create device for M1 recording electrode
        recording_device = nwbfile.create_device(
            name="DeviceMicroelectrodeRecording",
            description="Glass-coated PtIr microelectrode mounted in hydraulic microdrive (MO-95, Narishige Intl., Tokyo). "
            "Signal amplified 10^4, bandpass filtered 0.3-10kHz. Sampling: 20kHz for unit discrimination.",
        )

        # Create devices for chronically implanted stimulation electrodes
        # These are documented as devices even though they're not in the electrodes table
        # (stimulation electrode metadata is in StimulationElectrodesTable in the antidromic_identification module)
        nwbfile.create_device(
            name="DeviceMicrowirePeduncleStimulation",
            description="Custom-built PtIr microwire electrode for antidromic stimulation in cerebral peduncle. "
            "Chronically implanted for PTN identification.",
        )
        nwbfile.create_device(
            name="DeviceMicrowirePutamenStimulation1",
            description="Custom-built PtIr microwire electrode 1 of 3 for antidromic stimulation in posterolateral putamen. "
            "Chronically implanted for CSN identification.",
        )
        nwbfile.create_device(
            name="DeviceMicrowirePutamenStimulation2",
            description="Custom-built PtIr microwire electrode 2 of 3 for antidromic stimulation in posterolateral putamen. "
            "Chronically implanted for CSN identification.",
        )
        nwbfile.create_device(
            name="DeviceMicrowirePutamenStimulation3",
            description="Custom-built PtIr microwire electrode 3 of 3 for antidromic stimulation in posterolateral putamen. "
            "Chronically implanted for CSN identification.",
        )
        nwbfile.create_device(
            name="DeviceMicrowireThalamicStimulation",
            description="Custom-built PtIr microwire electrode for antidromic stimulation in VL thalamus. "
            "Chronically implanted for thalamocortical projection identification.",
        )
        nwbfile.create_device(
            name="DeviceMicrowireSTNStimulation",
            description="Custom-built PtIr microwire electrode for antidromic stimulation in subthalamic nucleus (STN). "
            "Chronically implanted for STN projection identification.",
        )

        # Recording electrode group for M1 chamber (left hemisphere)
        recording_electrode_group = nwbfile.create_electrode_group(
            name="ElectrodeGroupMicroelectrodeRecording",
            description="Left primary motor cortex recording within chamber-relative coordinate system. "
            "Chamber surgically positioned over left M1. Daily positions relative to chamber center. "
            "Functional verification via microstimulation (≤40μA, 10 pulses at 300Hz).",
            location="Primary motor cortex (M1), area 4, arm area",
            device=recording_device,
        )

        # Add custom columns for chamber grid coordinates and recording system metadata
        nwbfile.add_electrode_column(
            name="chamber_grid_ap_mm",
            description=(
                "Chamber grid position along the anterior-posterior axis, relative to chamber center "
                "(mm, positive = posterior). Recordings span -7 to 0 mm (all anterior to chamber center). "
                "NaN for stimulation electrodes."
            ),
        )
        nwbfile.add_electrode_column(
            name="chamber_grid_ml_mm",
            description=(
                "Chamber grid position along the medial-lateral axis, relative to chamber center "
                "(mm, positive = right). Recordings span -6 to -2 mm (all in left hemisphere). "
                "NaN for stimulation electrodes."
            ),
        )
        nwbfile.add_electrode_column(
            name="chamber_insertion_depth_mm",
            description=(
                "Electrode insertion depth from chamber reference point "
                "(mm, positive = deeper, range: 8.4-27.6mm). NaN for stimulation electrodes."
            ),
        )
        nwbfile.add_electrode_column(
            name="icms_effect",
            description=(
                "Movement evoked by intracortical microstimulation (ICMS) at recording site "
                "(10 biphasic pulses at 300 Hz, typically at or below 20 uA). "
                "Microexcitability at low currents is a hallmark of primary motor cortex. "
                "Values: movement description (e.g. 'wrist ext.', 'finger flex'), "
                "'NT' (not tested), 'NR'/'nr' (no response)."
            ),
        )
        nwbfile.add_electrode_column(
            name="icms_threshold_uA",
            description=(
                "Minimum current (microamps) at which ICMS evoked movement at the recording site. "
                "Low thresholds (<30 uA) confirm primary motor cortex (M1) recording location. "
                "NaN if not tested or no response."
            ),
        )
        # Use D99 atlas ACx coordinates when available
        # ACx convention: A_P_acx (+anterior), M_L_acx (+lateral, left hemisphere), Depth_acx (+superior/dorsal)
        ap_acx = self.session_info["A_P_acx"]
        ml_acx = self.session_info["M_L_acx"]
        depth_acx = self.session_info["Depth_acx"]
        has_acx = not (math.isnan(ap_acx) or math.isnan(ml_acx) or math.isnan(depth_acx))

        if has_acx:
            d99_full_name, d99_abbreviation = lookup_d99_region(ap_acx, ml_acx, depth_acx)
            electrode_location = d99_full_name

            # Convert ACx convention to D99 RAS:
            # R = -M_L (left hemisphere lateral is negative R)
            # A = A_P (source A_P is +anterior, same as RAS)
            # S = Depth (both +superior/dorsal)
            d99_r = -ml_acx
            d99_a = ap_acx
            d99_s = depth_acx

            # Look up precomputed NMT and MEBRAINS coordinates (avoids calling ANTs at runtime)
            nmt_r, nmt_a, nmt_s, mebrains_r, mebrains_a, mebrains_s = lookup_warped_coordinates(d99_r, d99_a, d99_s)
        else:
            electrode_location = "Primary motor cortex (M1), area 4, arm area"

        # Standard NWB x/y/z: NMT v2.0-sym coordinates in PIR convention (microns).
        if has_acx:
            x_pir = -nmt_a * 1000.0  # +anterior -> +posterior, mm -> um
            y_pir = -nmt_s * 1000.0  # +superior -> +inferior, mm -> um
            z_pir = nmt_r * 1000.0   # +right stays +right, mm -> um
        else:
            x_pir = float("nan")
            y_pir = float("nan")
            z_pir = float("nan")

        # Add recording electrode with chamber grid coordinates
        nwbfile.add_electrode(
            x=x_pir,
            y=y_pir,
            z=z_pir,
            imp=float("nan"),  # Electrode impedance not recorded
            location=electrode_location,
            filtering="0.3-10kHz bandpass for spikes, 1-100Hz for LFP when available",
            group=recording_electrode_group,
            chamber_grid_ap_mm=-self.session_info["A_P"],
            chamber_grid_ml_mm=self.session_info["M_L"],
            chamber_insertion_depth_mm=self.session_info["Depth"],
            icms_effect=_normalize_icms_effect(self.session_info.get("Microstim_Effect", "")),
            icms_threshold_uA=_to_float_or_nan(self.session_info.get("Microstim_Threshold")),
        )

        # Add atlas coordinates via ndx-anatomical-localization if available
        if has_acx:
            # D99 space and coordinates table
            d99_space = Space(
                name="D99",
                space_name="D99",
                origin="anterior commissure",
                units="mm",
                orientation="RAS",
            )

            d99_coordinates_table = AnatomicalCoordinatesTable(
                name="D99AtlasCoordinates",
                target=nwbfile.electrodes,
                description=(
                    "Recording electrode coordinates in D99 macaque atlas space (RAS orientation, mm). "
                    "Origin: anterior commissure. "
                    "Coordinates computed by Dr. Robert Turner from chamber-relative positions using "
                    "the known chamber placement geometry (AP offset to AC and 35-degree coronal tilt). "
                    "See: https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/nonhuman/macaque_tempatl/atlas_d99v2.html"
                ),
                method=(
                    "Coordinates transformed from chamber-relative positions to D99 atlas space "
                    "by Dr. Robert Turner (data author) using a geometric transformation: "
                    "constant AP offset (-8.2 mm, chamber center to anterior commissure) "
                    "and 35-degree rotation in the coronal plane (coupling ML and Depth to atlas R and S axes). "
                    "No individual MRI registration was used."
                ),
                space=d99_space,
            )

            d99_coordinates_table.add_column(
                name="brain_region_id",
                description="D99 atlas region abbreviation (e.g. F1_(4), F2_(6DR/6DC), 3a/b)",
            )

            d99_coordinates_table.add_row(
                x=d99_r,
                y=d99_a,
                z=d99_s,
                localized_entity=0,  # Index into electrode table (single recording electrode)
                brain_region=d99_full_name,
                brain_region_id=d99_abbreviation,
            )

            localization = Localization()
            spaces_to_add = [d99_space]
            tables_to_add = [d99_coordinates_table]

            # NMT v2.0-sym space and coordinates table (via RheMAP nonlinear warp)
            nmt_space = Space(
                name="NMTv2sym",
                space_name="NMT_v2.0_sym",
                origin="ear bar zero",
                units="mm",
                orientation="RAS",
            )

            nmt_coordinates_table = AnatomicalCoordinatesTable(
                name="NMTv2symAtlasCoordinates",
                target=nwbfile.electrodes,
                description=(
                    "Recording electrode coordinates in NMT v2.0-sym (NIMH Macaque Template, symmetric) "
                    "atlas space (RAS orientation, mm). Origin: ear bar zero (EBZ). "
                    "Coordinates converted from D99 atlas space using a pre-computed nonlinear warp "
                    "from RheMAP (Sirmpilatze & Klink, 2020; DOI: 10.5281/zenodo.4748589). "
                    "See: https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/nonhuman/macaque_tempatl/template_nmtv2.html"
                ),
                method=(
                    "Coordinates first transformed from chamber-relative positions to D99 atlas space "
                    "by Dr. Robert Turner (geometric transformation: AP offset + 35-degree coronal rotation). "
                    "Then converted from D99 to NMT v2.0-sym using the pre-computed nonlinear composite warp "
                    "from RheMAP v1.3 (NMTv2.0-sym_to_D99_CompositeWarp.nii.gz, applied in reverse for points). "
                    "RAS-to-LPS conversion applied before ANTs warp, then reversed. "
                    "Region labels use CHARM level 4 parcellation (native to NMT), constrained to M1 "
                    "(primary_motor_cortex, index 79). Many electrodes land in the central sulcus fundus, "
                    "where post-mortem tissue shrinkage creates unlabeled gaps in the template that do not "
                    "exist in vivo. Rather than labeling these 'outside atlas', the nearest M1 voxel is found "
                    "and its distance stored (brain_region_distance_mm). All recording sites are confirmed M1 "
                    "by microstimulation (icms_threshold_uA column on the electrodes table). "
                    "Unconstrained nearest-neighbor was rejected because it snaps to somatosensory cortex (S1) "
                    "on the opposite bank of the sulcal gap, which is geometrically closer in the template "
                    "but functionally wrong."
                ),
                space=nmt_space,
            )

            charm_region_name, charm_region_id, charm_method, charm_distance = lookup_charm_m1(nmt_r, nmt_a, nmt_s)

            nmt_coordinates_table.add_column(
                name="brain_region_id",
                description="CHARM level 4 region from M1-constrained lookup in NMT space (M1 = index 79)",
            )
            nmt_coordinates_table.add_column(
                name="brain_region_lookup_method",
                description=(
                    "How the brain region was determined: "
                    "'exact' = coordinate falls directly on a CHARM M1 voxel, "
                    "'nearest_neighbor' = snapped to nearest M1 voxel within 5 mm, "
                    "'outside' = no M1 voxel within 5 mm"
                ),
            )
            nmt_coordinates_table.add_column(
                name="brain_region_distance_mm",
                description=(
                    "Euclidean distance (mm) from the electrode coordinate to the nearest CHARM M1 voxel. "
                    "0.0 for exact hits, positive for nearest-neighbor, NaN if outside the 5 mm cap."
                ),
            )

            nmt_coordinates_table.add_row(
                x=nmt_r,
                y=nmt_a,
                z=nmt_s,
                localized_entity=0,
                brain_region=charm_region_name,
                brain_region_id=charm_region_id,
                brain_region_lookup_method=charm_method,
                brain_region_distance_mm=charm_distance,
            )

            spaces_to_add.append(nmt_space)
            tables_to_add.append(nmt_coordinates_table)

            # MEBRAINS space and coordinates table (via RheMAP nonlinear warp)

            mebrains_space = Space(
                name="MEBRAINS",
                space_name="MEBRAINS_1.0",
                origin="anterior commissure",
                units="mm",
                orientation="RAS",
            )

            mebrains_coordinates_table = AnatomicalCoordinatesTable(
                name="MEBRAINSAtlasCoordinates",
                target=nwbfile.electrodes,
                description=(
                    "Recording electrode coordinates in MEBRAINS 1.0 (population-based macaque template) "
                    "atlas space (RAS orientation, mm). Origin: anterior commissure. "
                    "Coordinates converted from D99 atlas space using a pre-computed nonlinear warp "
                    "from RheMAP (G-NODE repository: https://gin.g-node.org/ChrisKlink/RheMAP). "
                    "See: https://doi.org/10.1162/imag_a_00077"
                ),
                method=(
                    "Coordinates first transformed from chamber-relative positions to D99 atlas space "
                    "by Dr. Robert Turner (geometric transformation: AP offset + 35-degree coronal rotation). "
                    "Then converted from D99 to MEBRAINS 1.0 using the pre-computed nonlinear composite warp "
                    "from RheMAP (MEBRAINS_to_D99_CompositeWarp.nii.gz, applied in reverse for points). "
                    "RAS-to-LPS conversion applied before ANTs warp, then reversed. "
                    "Region labels use the MEBRAINS parcellation (Julich Brain Macaque Maps), constrained to "
                    "M1 subdivisions 4a (anterior) and 4p (posterior). MEBRAINS has wider sulcal gaps than D99 "
                    "due to post-mortem tissue processing, causing many electrodes to land in unlabeled voxels "
                    "at the central sulcus fundus. The nearest M1 (4a or 4p) voxel is found and its distance "
                    "stored (brain_region_distance_mm). The 4a/4p distinction indicates whether the electrode "
                    "is closer to anterior or posterior primary motor cortex. All recording sites are confirmed "
                    "M1 by microstimulation (icms_threshold_uA column on the electrodes table)."
                ),
                space=mebrains_space,
            )

            mebrains_region_name, mebrains_region_id, mebrains_method, mebrains_distance = lookup_mebrains_m1(
                mebrains_r, mebrains_a, mebrains_s
            )

            mebrains_coordinates_table.add_column(
                name="brain_region_id",
                description="MEBRAINS M1 label ID from M1-constrained lookup (301=4a left, 303=4p left)",
            )
            mebrains_coordinates_table.add_column(
                name="brain_region_lookup_method",
                description=(
                    "How the brain region was determined: "
                    "'exact' = coordinate falls directly on a MEBRAINS 4a/4p voxel, "
                    "'nearest_neighbor' = snapped to nearest M1 (4a or 4p) voxel within 5 mm, "
                    "'outside' = no M1 voxel within 5 mm"
                ),
            )
            mebrains_coordinates_table.add_column(
                name="brain_region_distance_mm",
                description=(
                    "Euclidean distance (mm) from the electrode coordinate to the nearest MEBRAINS M1 voxel. "
                    "0.0 for exact hits, positive for nearest-neighbor, NaN if outside the 5 mm cap."
                ),
            )

            mebrains_coordinates_table.add_row(
                x=mebrains_r,
                y=mebrains_a,
                z=mebrains_s,
                localized_entity=0,
                brain_region=mebrains_region_name,
                brain_region_id=mebrains_region_id,
                brain_region_lookup_method=mebrains_method,
                brain_region_distance_mm=mebrains_distance,
            )

            spaces_to_add.append(mebrains_space)
            tables_to_add.append(mebrains_coordinates_table)

            localization.add_spaces(spaces_to_add)
            # Add localization to the NWBFile before adding the coordinates tables,
            # so that both the DynamicTableRegion (localized_entity) and its target
            # (nwbfile.electrodes) share a common ancestor during validation.
            nwbfile.add_lab_meta_data(localization)
            localization.add_anatomical_coordinates_tables(tables_to_add)

        if self.verbose:
            print(f"Added electrode configuration: 1 recording electrode in electrodes table")
            if has_acx:
                print(f"Added D99 atlas coordinates (RAS mm): R={d99_r:.2f}, A={d99_a:.2f}, S={d99_s:.2f}")
                print(f"D99 region: {d99_full_name} ({d99_abbreviation})")
                print(f"Added NMT v2.0-sym coordinates (RAS mm): R={nmt_r:.2f}, A={nmt_a:.2f}, S={nmt_s:.2f}")
                print(f"NMT CHARM M1: {charm_region_id} ({charm_method}, {charm_distance:.2f} mm)")
                print(f"Added MEBRAINS coordinates (RAS mm): R={mebrains_r:.2f}, A={mebrains_a:.2f}, S={mebrains_s:.2f}")
                print(f"MEBRAINS M1: {mebrains_region_name} ({mebrains_method}, {mebrains_distance:.2f} mm)")